---
title: "BiodivMdlPred_Fish_One_var_chngs"
author: "Jenny Rogers"
date: "2023-03-02"
output: html_document
---


```{r}

library(tidyverse)
library(sf)
library(glmmTMB)
library(readxl)



```

proportional abundance predictions
```{r}

load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")


file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects")


for (i in 1:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  NHDplusV2_NewEngCrop$baseline_predict <- predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response")
  
ggplot(data = NHDplusV2_NewEngCrop)+
  geom_sf(aes(color = baseline_predict))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)
  
}


#stream reach scale spp proportional abuncnae

#predict the model on the historical data
pred_data <- dat[,11:42]
predict <- predict(mdl, newdata = pred_data, type = "response")
compare <- data.frame("propabun" = dat$propabun, "prediction" = predict)



#plot
dat$prediction <- compare$prediction
tmp <- left_join(fish_shp, dat, by ="UID") %>% 
  mutate(pres = as.factor(ifelse(prediction > 0.1, 1, 0)))
ggplot(data = tmp[!is.na(tmp$prediction),])+
  geom_sf(aes(fill=pres, size = prediction), pch = 21, col = "black")

ggplot(data = tmp[!is.na(tmp$prediction),])+
  geom_sf(aes(fill= prediction, size = prediction), pch = 21, col = "black")

#predict the model on all of the flows lines, not just the training data 



```
Predict presence absence of each fish in baseline years

```{r}

load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")

#need to scal the variavles
test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)

test <- test[,c(7:8, 10:39)]

test <- data.frame(scale(test))

NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1:6, 9)], test)





file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
names(predictions)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions <- cbind(predictions, tmp)
  
  
}


#join the predictions to the list of comids
NHDplusV2_NewEngCrop_baseline <- cbind(NHDplusV2_NewEngCrop, predictions)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_baseline)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC12s that have an average P(occurrece)>0.05 for the baseline conditions
head(NHDplusV2_NewEngCrop_baseline)
tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count = n(),
            avg_prob = mean(mean_prob))









#annual mean summer temp

NHDplusV2_NewEngCrop_sumtmp <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_sumtmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_sumtmp, type = "response"))
names(predictions_sumtmp)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_sumtmp, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_sumtmp <- cbind(predictions_sumtmp, tmp)
  
  
}


#join the predictions_sumtmp to the list of comids
NHDplusV2_NewEngCrop_sumtmp <- cbind(NHDplusV2_NewEngCrop_sumtmp, predictions_sumtmp)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_sumtmp)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the mgmt conditions
head(NHDplusV2_NewEngCrop_sumtmp)
tmp_sumtmp <- NHDplusV2_NewEngCrop_sumtmp %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, , common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_sumtmp = n(),
            avg_prob_sumtmp = mean(mean_prob))






#BFI_HIST

NHDplusV2_NewEngCrop_BFI_HIST <- NHDplusV2_NewEngCrop %>% 
  mutate(BFI_HIST = BFI_HIST + 2
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_BFI_HIST <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_BFI_HIST, type = "response"))
names(predictions_BFI_HIST)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_BFI_HIST, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_BFI_HIST <- cbind(predictions_BFI_HIST, tmp)
  
  
}


#join the predictions_ccdvlp to the list of comids
NHDplusV2_NewEngCrop_BFI_HIST <- cbind(NHDplusV2_NewEngCrop_BFI_HIST, predictions_BFI_HIST)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_BFI_HIST)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the BFI_HIST conditions
head(NHDplusV2_NewEngCrop_BFI_HIST)
tmp_BFI_HIST <- NHDplusV2_NewEngCrop_BFI_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_BFI_HIST = n(),
            avg_prob_BFI_HIST = mean(mean_prob))







#LO7Q1DT_HIST 

NHDplusV2_NewEngCrop_LO7Q1DT_HIST <- NHDplusV2_NewEngCrop %>% 
  mutate(LO7Q1DT_HIST = LO7Q1DT_HIST + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_LO7Q1DT_HIST <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_LO7Q1DT_HIST, type = "response"))
names(predictions_LO7Q1DT_HIST)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_LO7Q1DT_HIST, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_LO7Q1DT_HIST <- cbind(predictions_LO7Q1DT_HIST, tmp)
  
  
}


#join the predictions_LO7Q1DT_HIST to the list of comids
NHDplusV2_NewEngCrop_LO7Q1DT_HIST <- cbind(NHDplusV2_NewEngCrop_LO7Q1DT_HIST, predictions_LO7Q1DT_HIST)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_LO7Q1DT_HIST)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the LO7Q1DT_HIST conditions
head(NHDplusV2_NewEngCrop_LO7Q1DT_HIST)
tmp_LO7Q1DT_HIST <- NHDplusV2_NewEngCrop_LO7Q1DT_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_LO7Q1DT_HIST = n(),
            avg_prob_LO7Q1DT_HIST = mean(mean_prob))







#W95_HIST 

NHDplusV2_NewEngCrop_W95_HIST <- NHDplusV2_NewEngCrop %>% 
  mutate(W95_HIST = W95_HIST + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_W95_HIST <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_W95_HIST, type = "response"))
names(predictions_W95_HIST)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_W95_HIST, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_W95_HIST <- cbind(predictions_W95_HIST, tmp)
  
  
}


#join the predictions_W95_HIST to the list of comids
NHDplusV2_NewEngCrop_W95_HIST <- cbind(NHDplusV2_NewEngCrop_W95_HIST, predictions_W95_HIST)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the W95_HIST conditions
head(NHDplusV2_NewEngCrop_W95_HIST)
tmp_W95_HIST <- NHDplusV2_NewEngCrop_W95_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_W95_HIST = n(),
            avg_prob_W95_HIST = mean(mean_prob))









#BFIWs 

NHDplusV2_NewEngCrop_BFIWs <- NHDplusV2_NewEngCrop %>% 
  mutate(BFIWs = BFIWs + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_BFIWs <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_BFIWs, type = "response"))
names(predictions_BFIWs)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_BFIWs, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_BFIWs <- cbind(predictions_BFIWs, tmp)
  
  
}


#join the predictions_BFIWs to the list of comids
NHDplusV2_NewEngCrop_BFIWs <- cbind(NHDplusV2_NewEngCrop_BFIWs, predictions_BFIWs)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the BFIWs conditions
head(NHDplusV2_NewEngCrop_BFIWs)
tmp_BFIWs <- NHDplusV2_NewEngCrop_BFIWs %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_BFIWs = n(),
            avg_prob_BFIWs = mean(mean_prob))






#WtDepWs 

NHDplusV2_NewEngCrop_WtDepWs <- NHDplusV2_NewEngCrop %>% 
  mutate(WtDepWs = WtDepWs + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_WtDepWs <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_WtDepWs, type = "response"))
names(predictions_WtDepWs)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_WtDepWs, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_WtDepWs <- cbind(predictions_WtDepWs, tmp)
  
  
}


#join the predictions_WtDepWs to the list of comids
NHDplusV2_NewEngCrop_WtDepWs <- cbind(NHDplusV2_NewEngCrop_WtDepWs, predictions_WtDepWs)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the WtDepWs conditions
head(NHDplusV2_NewEngCrop_WtDepWs)
tmp_WtDepWs <- NHDplusV2_NewEngCrop_WtDepWs %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_WtDepWs = n(),
            avg_prob_WtDepWs = mean(mean_prob))







#PctOw_Ws 

NHDplusV2_NewEngCrop_PctOw_Ws <- NHDplusV2_NewEngCrop %>% 
  mutate(PctOw_Ws = PctOw_Ws + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_PctOw_Ws <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_PctOw_Ws, type = "response"))
names(predictions_PctOw_Ws)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_PctOw_Ws, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_PctOw_Ws <- cbind(predictions_PctOw_Ws, tmp)
  
  
}


#join the predictions_WtDepWs to the list of comids
NHDplusV2_NewEngCrop_PctOw_Ws <- cbind(NHDplusV2_NewEngCrop_PctOw_Ws, predictions_PctOw_Ws)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the PctOw_Ws conditions
head(NHDplusV2_NewEngCrop_PctOw_Ws)
tmp_PctOw_Ws <- NHDplusV2_NewEngCrop_PctOw_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_PctOw_Ws = n(),
            avg_prob_PctOw_Ws = mean(mean_prob))








#PctImp_Ws 

NHDplusV2_NewEngCrop_PctImp_Ws <- NHDplusV2_NewEngCrop %>% 
  mutate(PctImp_Ws = PctImp_Ws + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_PctImp_Ws <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_PctImp_Ws, type = "response"))
names(predictions_PctImp_Ws)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_PctImp_Ws, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_PctImp_Ws <- cbind(predictions_PctImp_Ws, tmp)
  
  
}


#join the predictions_PctImp_Ws to the list of comids
NHDplusV2_NewEngCrop_PctImp_Ws <- cbind(NHDplusV2_NewEngCrop_PctImp_Ws, predictions_PctImp_Ws)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the PctImp_Ws conditions
head(NHDplusV2_NewEngCrop_PctImp_Ws)
tmp_PctImp_Ws <- NHDplusV2_NewEngCrop_PctImp_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_PctImp_Ws = n(),
            avg_prob_PctImp_Ws = mean(mean_prob))






#pctAg_Ws 

NHDplusV2_NewEngCrop_pctAg_Ws <- NHDplusV2_NewEngCrop %>% 
  mutate(pctAg_Ws = pctAg_Ws + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_pctAg_Ws <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_pctAg_Ws, type = "response"))
names(predictions_pctAg_Ws)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_pctAg_Ws, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_pctAg_Ws <- cbind(predictions_pctAg_Ws, tmp)
  
  
}


#join the predictions_pctAg_Ws to the list of comids
NHDplusV2_NewEngCrop_pctAg_Ws <- cbind(NHDplusV2_NewEngCrop_pctAg_Ws, predictions_pctAg_Ws)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the pctAg_Ws conditions
head(NHDplusV2_NewEngCrop_pctAg_Ws)
tmp_pctAg_Ws <- NHDplusV2_NewEngCrop_pctAg_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_pctAg_Ws = n(),
            avg_prob_pctAg_Ws = mean(mean_prob))








#pctWetland_Cat 

NHDplusV2_NewEngCrop_pctWetland_Cat <- NHDplusV2_NewEngCrop %>% 
  mutate(pctWetland_Cat = pctWetland_Cat + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_pctWetland_Cat <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_pctWetland_Cat, type = "response"))
names(predictions_pctWetland_Cat)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_pctWetland_Cat, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_pctWetland_Cat <- cbind(predictions_pctWetland_Cat, tmp)
  
  
}


#join the predictions_pctWetland_Cat to the list of comids
NHDplusV2_NewEngCrop_pctWetland_Cat <- cbind(NHDplusV2_NewEngCrop_pctWetland_Cat, predictions_pctWetland_Cat)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the pctWetland_Cat conditions
head(NHDplusV2_NewEngCrop_pctWetland_Cat)
tmp_pctWetland_Cat <- NHDplusV2_NewEngCrop_pctWetland_Cat %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_pctWetland_Cat = n(),
            avg_prob_pctWetland_Cat = mean(mean_prob))






#logPctOw_Cat 

NHDplusV2_NewEngCrop_logPctOw_Cat <- NHDplusV2_NewEngCrop %>% 
  mutate(logPctOw_Cat = logPctOw_Cat + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_logPctOw_Cat <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logPctOw_Cat, type = "response"))
names(predictions_logPctOw_Cat)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logPctOw_Cat, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_logPctOw_Cat <- cbind(predictions_logPctOw_Cat, tmp)
  
  
}


#join the predictions_logPctOw_Cat to the list of comids
NHDplusV2_NewEngCrop_logPctOw_Cat <- cbind(NHDplusV2_NewEngCrop_logPctOw_Cat, predictions_logPctOw_Cat)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the logPctOw_Cat conditions
head(NHDplusV2_NewEngCrop_logPctOw_Cat)
tmp_logPctOw_Cat <- NHDplusV2_NewEngCrop_logPctOw_Cat %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_logPctOw_Cat = n(),
            avg_prob_logPctOw_Cat = mean(mean_prob))





#logMJJA_HIST 

NHDplusV2_NewEngCrop_logMJJA_HIST <- NHDplusV2_NewEngCrop %>% 
  mutate(logMJJA_HIST = logMJJA_HIST + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_logMJJA_HIST <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logMJJA_HIST, type = "response"))
names(predictions_logMJJA_HIST)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logMJJA_HIST, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_logMJJA_HIST <- cbind(predictions_logMJJA_HIST, tmp)
  
  
}


#join the predictions_logMJJA_HIST to the list of comids
NHDplusV2_NewEngCrop_logMJJA_HIST <- cbind(NHDplusV2_NewEngCrop_logMJJA_HIST, predictions_logMJJA_HIST)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the logMJJA_HIST conditions
head(NHDplusV2_NewEngCrop_logMJJA_HIST)
tmp_logMJJA_HIST <- NHDplusV2_NewEngCrop_logMJJA_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_logMJJA_HIST = n(),
            avg_prob_logMJJA_HIST = mean(mean_prob))





#logRdCrsCat 

NHDplusV2_NewEngCrop_logRdCrsCat <- NHDplusV2_NewEngCrop %>% 
  mutate(logRdCrsCat = logRdCrsCat + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_logRdCrsCat <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logRdCrsCat, type = "response"))
names(predictions_logRdCrsCat)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_logRdCrsCat, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_logRdCrsCat <- cbind(predictions_logRdCrsCat, tmp)
  
  
}


#join the predictions_logRdCrsCat to the list of comids
NHDplusV2_NewEngCrop_logRdCrsCat <- cbind(NHDplusV2_NewEngCrop_logRdCrsCat, predictions_logRdCrsCat)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the logRdCrsCat conditions
head(NHDplusV2_NewEngCrop_logRdCrsCat)
tmp_logRdCrsCat <- NHDplusV2_NewEngCrop_logRdCrsCat %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_logRdCrsCat = n(),
            avg_prob_logRdCrsCat = mean(mean_prob))







#huc12_damden_sqkm 

NHDplusV2_NewEngCrop_huc12_damden_sqkm <- NHDplusV2_NewEngCrop %>% 
  mutate(huc12_damden_sqkm = huc12_damden_sqkm + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_huc12_damden_sqkm <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_huc12_damden_sqkm, type = "response"))
names(predictions_huc12_damden_sqkm)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_huc12_damden_sqkm, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_huc12_damden_sqkm <- cbind(predictions_huc12_damden_sqkm, tmp)
  
  
}


#join the predictions_logRdCrsCat to the list of comids
NHDplusV2_NewEngCrop_huc12_damden_sqkm <- cbind(NHDplusV2_NewEngCrop_huc12_damden_sqkm, predictions_huc12_damden_sqkm)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the huc12_damden_sqkm conditions
head(NHDplusV2_NewEngCrop_huc12_damden_sqkm)
tmp_huc12_damden_sqkm <- NHDplusV2_NewEngCrop_huc12_damden_sqkm %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_huc12_damden_sqkm = n(),
            avg_prob_huc12_damden_sqkm = mean(mean_prob))







#huc8_damcount 

NHDplusV2_NewEngCrop_huc8_damcount <- NHDplusV2_NewEngCrop %>% 
  mutate(huc8_damcount = huc8_damcount + 2,
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_huc8_damcount <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_huc8_damcount, type = "response"))
names(predictions_huc8_damcount)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_huc8_damcount, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_huc8_damcount <- cbind(predictions_huc8_damcount, tmp)
  
  
}


#join the predictions_huc8_damcount to the list of comids
NHDplusV2_NewEngCrop_huc8_damcount <- cbind(NHDplusV2_NewEngCrop_huc8_damcount, predictions_huc8_damcount)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the huc8_damcount conditions
head(NHDplusV2_NewEngCrop_huc8_damcount)
tmp_huc8_damcount <- NHDplusV2_NewEngCrop_huc8_damcount %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_huc8_damcount = n(),
            avg_prob_huc8_damcount = mean(mean_prob))








compare <- full_join(tmp_baseline, tmp_sumtmp, by  = "common_name")
compare <- full_join(compare, tmp_BFI_HIST , by  = "common_name")
compare <- full_join(compare, tmp_LO7Q1DT_HIST, by  = "common_name")
compare <- full_join(compare, tmp_W95_HIST, by  = "common_name")
compare <- full_join(compare, tmp_BFIWs, by  = "common_name")
compare <- full_join(compare, tmp_WtDepWs, by  = "common_name")
compare <- full_join(compare, tmp_PctOw_Ws, by  = "common_name")
compare <- full_join(compare, tmp_PctImp_Ws, by  = "common_name")
compare <- full_join(compare, tmp_pctAg_Ws, by  = "common_name")
compare <- full_join(compare, tmp_pctWetland_Cat, by  = "common_name")
compare <- full_join(compare, tmp_logPctOw_Cat, by  = "common_name")
compare <- full_join(compare, tmp_logMJJA_HIST, by  = "common_name")
compare <- full_join(compare, tmp_logRdCrsCat, by  = "common_name")
compare <- full_join(compare, tmp_huc12_damden_sqkm, by  = "common_name")
compare <- full_join(compare, tmp_huc8_damcount, by  = "common_name")


names(compare)

compare <- compare %>% 
  mutate(base_LO7Q1DT_HIST = round(((count_LO7Q1DT_HIST - count)/count*100),0),
         base_BFI_HIST = round(((count_BFI_HIST - count )/count*100),0),
         base_sumtmp = round(((count_sumtmp - count)/count*100),0),
         base_W95_HIST = round(((count_W95_HIST - count)/count*100),0),
         base_BFIWs = round(((count_BFIWs - count )/count*100),0),
         base_WtDepWs = round(((count_WtDepWs - count)/count*100),0),
         base_PctOw_Ws = round(((count_PctOw_Ws - count)/count*100),0),
         base_PctImp_Ws = round(((count_PctImp_Ws - count )/count*100),0),
         base_pctAg_Ws = round(((count_pctAg_Ws - count)/count*100),0),
         base_pctWetland_Cat = round(((count_pctWetland_Cat - count)/count*100),0),
         base_logPctOw_Cat = round(((count_logPctOw_Cat - count )/count*100),0),
         base_logMJJA_HIST = round(((count_logMJJA_HIST - count)/count*100),0),
         base_logRdCrsCat = round(((count_logRdCrsCat - count)/count*100),0),
         base_huc12_damden_sqkm = round(((count_huc12_damden_sqkm - count )/count*100),0),
         base_huc8_damcount = round(((count_huc8_damcount - count)/count*100),0),
         
         
         
         basep_LO7Q1DT_HISTp = round(((avg_prob_LO7Q1DT_HIST - avg_prob)/avg_prob*100),0),
         basep_BFI_HISTp = round(((avg_prob_BFI_HIST - avg_prob)/avg_prob*100),0),
         basep_sumtmpp = round(((avg_prob_sumtmp - avg_prob)/avg_prob*100),0),
         basep_W95_HISTp = round(((avg_prob_W95_HIST - avg_prob)/avg_prob*100),0),
         basep_BFIWsp = round(((avg_prob_BFIWs - avg_prob)/avg_prob*100),0),
         basep_WtDepWsp = round(((avg_prob_WtDepWs - avg_prob)/avg_prob*100),0),
         basep_PctOw_Wsp = round(((avg_prob_PctOw_Ws - avg_prob)/avg_prob*100),0),
         basep_PctImp_Wsp = round(((avg_prob_PctImp_Ws - avg_prob)/avg_prob*100),0),
         basep_pctAg_Wsp = round(((avg_prob_pctAg_Ws - avg_prob)/avg_prob*100),0),
         basep_pctWetland_Catp = round(((avg_prob_pctWetland_Cat - avg_prob)/avg_prob*100),0),
         basep_logPctOw_Catp = round(((avg_prob_logPctOw_Cat - avg_prob)/avg_prob*100),0),
         basep_logMJJA_HISTp = round(((avg_prob_logMJJA_HIST - avg_prob)/avg_prob*100),0),
         basep_logRdCrsCatp = round(((avg_prob_logRdCrsCat - avg_prob)/avg_prob*100),0),
         basep_huc12_damden_sqkmp = round(((avg_prob_huc12_damden_sqkm - avg_prob)/avg_prob*100),0),
         basep_huc8_damcountp = round(((avg_prob_huc8_damcount - avg_prob)/avg_prob*100),0)
         )

compare$common_name <- gsub(".rds", "", compare$common_name)

compare$common_name <- gsub("pres_", "", compare$common_name)

compare$common_name <- gsub("\\.", " ", compare$common_name)

#remove spp that didnt have model convergence
compare <- compare %>% 
  filter(! common_name %in% c("bowfin", "white catfish", "rosyside dace", 
                              "mimic shiner", "walleye", "round whitefish", 
                              "roseface shiner",  "spotfin shiner"))

load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_occurrence.RData")
names <- fish_occurrence %>% 
  select(common_name, scientific_name) %>% 
  unique()

compare <- left_join(compare, names, by = "common_name") %>% 
  select(scientific_name, 1:63) %>% 
  arrange(desc(count))

write.csv(compare, file = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/presabs_predictions.csv")






#LEFT OFF HERE 3-2-2023 NEED TO UPDATE BELOW BY DOING THIS FOR ALL 15 SCENARIOS


#calcuate spp richness by huc12 for each basin

#fish traits
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_traits.RData")
temperature <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 1,
                  range = cell_cols("A:H")) %>% 
  select(common_name, all) %>% 
  rename(tmp = all)
origin <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 2,
                  range = cell_cols("A:G"))%>% 
  pivot_longer(2:7, names_to = "state", values_to = "origin") %>% 
  filter(state == "MA") %>% 
  select(common_name, origin)
#Even though the origin vary by state, for now, were just going to use the MA designations


#### species richness by origin


tmp_sumtmp <- NHDplusV2_NewEngCrop_sumtmp %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_sumtmp$common_name <- gsub(".rds", "", tmp_sumtmp$common_name)
tmp_sumtmp$common_name <- gsub("pres_", "", tmp_sumtmp$common_name)
tmp_sumtmp$common_name <- gsub("\\.", " ", tmp_sumtmp$common_name)

tmp_sumtmp <- tmp_sumtmp %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_sumtmp = n()) %>% 
  pivot_wider(names_from = origin, values_from = rich_sumtmp) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_sumtmp = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



tmp_BFI_HIST <- NHDplusV2_NewEngCrop_BFI_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_BFI_HIST$common_name <- gsub(".rds", "", tmp_BFI_HIST$common_name)
tmp_BFI_HIST$common_name <- gsub("pres_", "", tmp_BFI_HIST$common_name)
tmp_BFI_HIST$common_name <- gsub("\\.", " ", tmp_BFI_HIST$common_name)

tmp_BFI_HIST <-  tmp_BFI_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_BFI_HIST = n())%>% 
  pivot_wider(names_from = origin, values_from = rich_BFI_HIST) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_BFI_HIST = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)


tmp_LO7Q1DT_HIST <- NHDplusV2_NewEngCrop_LO7Q1DT_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_LO7Q1DT_HIST$common_name <- gsub(".rds", "", tmp_LO7Q1DT_HIST$common_name)
tmp_LO7Q1DT_HIST$common_name <- gsub("pres_", "", tmp_LO7Q1DT_HIST$common_name)
tmp_LO7Q1DT_HIST$common_name <- gsub("\\.", " ", tmp_LO7Q1DT_HIST$common_name)

tmp_LO7Q1DT_HIST <- tmp_LO7Q1DT_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_LO7Q1DT_HIST = n()) %>% 
  pivot_wider(names_from = origin, values_from = rich_LO7Q1DT_HIST) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_LO7Q1DT_HIST = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_baseline$common_name <- gsub(".rds", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("pres_", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("\\.", " ", tmp_baseline$common_name)

tmp_baseline <- tmp_baseline %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_baseline = n())%>% 
  pivot_wider(names_from = origin, values_from = rich_baseline) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_baseline = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")

states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")


# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


# huc8 <- left_join(huc8, tmp_baseline, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_cc, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccdvlp, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccmgmt, by = "huc8_name")

huc12 <- left_join(huc12, tmp_baseline, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_sumtmp, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_BFI_HIST, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_LO7Q1DT_HIST, by = c("huc12_tnmid", "huc12_name"))

#calcuate change in climate change from baseline, but change in the other two from climate change
huc12 <- huc12 %>% 
  mutate(change_BFI_HIST = prop_native_BFI_HIST - prop_native_sumtmp,
         change_LO7Q1DT_HIST = prop_native_LO7Q1DT_HIST - prop_native_sumtmp)

#plot absolute values of proportaional richness of native spp
huc12a <- huc12 %>% 
  select(3:7) %>% 
  pivot_longer(2:5, names_to = "scenario", values_to = "prop_richness") %>% 
  filter(!is.na(prop_richness))
huc12a$scenario[huc12a$scenario == "prop_native_baseline"] <- "Baseline"
huc12a$scenario[huc12a$scenario == "prop_native_sumtmp"] <- "sumtmp"
huc12a$scenario[huc12a$scenario == "prop_native_BFI_HIST"] <- "BFI"
huc12a$scenario[huc12a$scenario == "prop_native_LO7Q1DT_HIST"] <- "LowFlowTIme"


ggplot(data = huc12a)+
  geom_sf(aes(fill = prop_richness), color = NA)+
  scale_fill_viridis_c()+
  facet_wrap(~scenario, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Native Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_native_spp_richness.png",
    plot = last_plot(),
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300
  )



#plot change of proportaional richness of native spp
huc12b <- huc12 %>% 
  select(3, 9, 10) %>% 
  pivot_longer(2:3, names_to = "scenario", values_to = "change") %>% 
  filter(!is.na(change))
huc12b$scenario[huc12b$scenario == "change_BFI_HIST"] <- "BFI_HIST"
huc12b$scenario[huc12b$scenario == "change_LO7Q1DT_HIST"] <- "LO7Q1DT_HIST"


ggplot(data = huc12b)+
  geom_sf(aes(fill = change), color = NA)+
  scale_fill_viridis_c(option = "magma")+
  facet_wrap(~scenario, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Change Prop Native Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_native_spp_richness_change.png",
    plot = last_plot(),
    width = 9,
    height = 12,
    units = "cm",
    dpi = 300
  )





#### species richness by temperature


tmp_sumtmp <- NHDplusV2_NewEngCrop_sumtmp %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_sumtmp$common_name <- gsub(".rds", "", tmp_sumtmp$common_name)
tmp_sumtmp$common_name <- gsub("pres_", "", tmp_sumtmp$common_name)
tmp_sumtmp$common_name <- gsub("\\.", " ", tmp_sumtmp$common_name)

tmp_sumtmp <- tmp_sumtmp %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_sumtmp = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_sumtmp) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_sumtmp = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)



tmp_BFI_HIST <- NHDplusV2_NewEngCrop_BFI_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_BFI_HIST$common_name <- gsub(".rds", "", tmp_BFI_HIST$common_name)
tmp_BFI_HIST$common_name <- gsub("pres_", "", tmp_BFI_HIST$common_name)
tmp_BFI_HIST$common_name <- gsub("\\.", " ", tmp_BFI_HIST$common_name)

tmp_BFI_HIST <-  tmp_BFI_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_BFI_HIST = n())%>% 
  pivot_wider(names_from = tmp, values_from = rich_BFI_HIST) %>% 
  mutate(sum = sum(warm, cold, cool, na.rm = T),
         prop_cold_BFI_HIST = cold/sum) %>% 
  select(-warm, -cold, -cool, -sum, -eury)


tmp_LO7Q1DT_HIST <- NHDplusV2_NewEngCrop_LO7Q1DT_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_LO7Q1DT_HIST$common_name <- gsub(".rds", "", tmp_LO7Q1DT_HIST$common_name)
tmp_LO7Q1DT_HIST$common_name <- gsub("pres_", "", tmp_LO7Q1DT_HIST$common_name)
tmp_LO7Q1DT_HIST$common_name <- gsub("\\.", " ", tmp_LO7Q1DT_HIST$common_name)

tmp_LO7Q1DT_HIST <- tmp_LO7Q1DT_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_LO7Q1DT_HIST = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_LO7Q1DT_HIST) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_LO7Q1DT_HIST = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_W95_HIST <- NHDplusV2_NewEngCrop_W95_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_W95_HIST$common_name <- gsub(".rds", "", tmp_W95_HIST$common_name)
tmp_W95_HIST$common_name <- gsub("pres_", "", tmp_W95_HIST$common_name)
tmp_W95_HIST$common_name <- gsub("\\.", " ", tmp_W95_HIST$common_name)

tmp_W95_HIST <- tmp_W95_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_W95_HIST = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_W95_HIST) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_W95_HIST = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_BFIWs <- NHDplusV2_NewEngCrop_W95_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_BFIWs$common_name <- gsub(".rds", "", tmp_BFIWs$common_name)
tmp_BFIWs$common_name <- gsub("pres_", "", tmp_BFIWs$common_name)
tmp_BFIWs$common_name <- gsub("\\.", " ", tmp_BFIWs$common_name)

tmp_BFIWs <- tmp_BFIWs %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_BFIWs = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_BFIWs) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_BFIWs = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_WtDepWs <- NHDplusV2_NewEngCrop_W95_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_WtDepWs$common_name <- gsub(".rds", "", tmp_WtDepWs$common_name)
tmp_WtDepWs$common_name <- gsub("pres_", "", tmp_WtDepWs$common_name)
tmp_WtDepWs$common_name <- gsub("\\.", " ", tmp_WtDepWs$common_name)

tmp_WtDepWs <- tmp_WtDepWs %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_WtDepWs = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_WtDepWs) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_WtDepWs = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_PctOw_Ws <- NHDplusV2_NewEngCrop_W95_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_PctOw_Ws$common_name <- gsub(".rds", "", tmp_PctOw_Ws$common_name)
tmp_PctOw_Ws$common_name <- gsub("pres_", "", tmp_PctOw_Ws$common_name)
tmp_PctOw_Ws$common_name <- gsub("\\.", " ", tmp_PctOw_Ws$common_name)

tmp_PctOw_Ws <- tmp_PctOw_Ws %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_PctOw_Ws = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_PctOw_Ws) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_PctOw_Ws = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)



tmp_PctImp_Ws <- NHDplusV2_NewEngCrop_PctImp_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_PctImp_Ws$common_name <- gsub(".rds", "", tmp_PctImp_Ws$common_name)
tmp_PctImp_Ws$common_name <- gsub("pres_", "", tmp_PctImp_Ws$common_name)
tmp_PctImp_Ws$common_name <- gsub("\\.", " ", tmp_PctImp_Ws$common_name)

tmp_PctImp_Ws <- tmp_PctImp_Ws %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_PctImp_Ws = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_PctImp_Ws) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_PctImp_Ws = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_pctAg_Ws <- NHDplusV2_NewEngCrop_PctImp_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_pctAg_Ws$common_name <- gsub(".rds", "", tmp_pctAg_Ws$common_name)
tmp_pctAg_Ws$common_name <- gsub("pres_", "", tmp_pctAg_Ws$common_name)
tmp_pctAg_Ws$common_name <- gsub("\\.", " ", tmp_pctAg_Ws$common_name)

tmp_pctAg_Ws <- tmp_pctAg_Ws %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_pctAg_Ws = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_pctAg_Ws) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_pctAg_Ws = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_pctWetland_Cat <- NHDplusV2_NewEngCrop_PctImp_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_pctWetland_Cat$common_name <- gsub(".rds", "", tmp_pctWetland_Cat$common_name)
tmp_pctWetland_Cat$common_name <- gsub("pres_", "", tmp_pctWetland_Cat$common_name)
tmp_pctWetland_Cat$common_name <- gsub("\\.", " ", tmp_pctWetland_Cat$common_name)

tmp_pctWetland_Cat <- tmp_pctWetland_Cat %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_pctWetland_Cat = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_pctWetland_Cat) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_pctWetland_Cat = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_logPctOw_Cat <- NHDplusV2_NewEngCrop_PctImp_Ws %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_logPctOw_Cat$common_name <- gsub(".rds", "", tmp_logPctOw_Cat$common_name)
tmp_logPctOw_Cat$common_name <- gsub("pres_", "", tmp_logPctOw_Cat$common_name)
tmp_logPctOw_Cat$common_name <- gsub("\\.", " ", tmp_logPctOw_Cat$common_name)

tmp_logPctOw_Cat <- tmp_logPctOw_Cat %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_logPctOw_Cat = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_logPctOw_Cat) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_logPctOw_Cat = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_logMJJA_HIST <- NHDplusV2_NewEngCrop_logMJJA_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_logMJJA_HIST$common_name <- gsub(".rds", "", tmp_logMJJA_HIST$common_name)
tmp_logMJJA_HIST$common_name <- gsub("pres_", "", tmp_logMJJA_HIST$common_name)
tmp_logMJJA_HIST$common_name <- gsub("\\.", " ", tmp_logMJJA_HIST$common_name)

tmp_logMJJA_HIST <- tmp_logMJJA_HIST %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_logMJJA_HIST = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_logMJJA_HIST) %>% 
  mutate(sum = sum(warm, cold, cool, na.rm = T),
         prop_cold_logMJJA_HIST = cold/sum) %>% 
  select(-warm, -cold, -cool, -sum)


tmp_logRdCrsCat <- NHDplusV2_NewEngCrop_logMJJA_HIST %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_logRdCrsCat$common_name <- gsub(".rds", "", tmp_logRdCrsCat$common_name)
tmp_logRdCrsCat$common_name <- gsub("pres_", "", tmp_logRdCrsCat$common_name)
tmp_logRdCrsCat$common_name <- gsub("\\.", " ", tmp_logRdCrsCat$common_name)

tmp_logRdCrsCat <- tmp_logRdCrsCat %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_logRdCrsCat = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_logRdCrsCat) %>% 
  mutate(sum = sum(warm, cold, cool,  na.rm = T),
         prop_cold_logRdCrsCat = cold/sum) %>% 
  select(-warm, -cold, -cool,  -sum)


tmp_huc12_damden_sqkm <- NHDplusV2_NewEngCrop_huc12_damden_sqkm %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_huc12_damden_sqkm$common_name <- gsub(".rds", "", tmp_huc12_damden_sqkm$common_name)
tmp_huc12_damden_sqkm$common_name <- gsub("pres_", "", tmp_huc12_damden_sqkm$common_name)
tmp_huc12_damden_sqkm$common_name <- gsub("\\.", " ", tmp_huc12_damden_sqkm$common_name)

tmp_huc12_damden_sqkm <- tmp_huc12_damden_sqkm %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_huc12_damden_sqkm = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_huc12_damden_sqkm) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_huc12_damden_sqkm = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_huc8_damcount <- NHDplusV2_NewEngCrop_huc8_damcount %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_huc8_damcount$common_name <- gsub(".rds", "", tmp_huc8_damcount$common_name)
tmp_huc8_damcount$common_name <- gsub("pres_", "", tmp_huc8_damcount$common_name)
tmp_huc8_damcount$common_name <- gsub("\\.", " ", tmp_huc8_damcount$common_name)

tmp_huc8_damcount <- tmp_huc8_damcount %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_huc8_damcount = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_huc8_damcount) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_huc8_damcount = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_baseline$common_name <- gsub(".rds", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("pres_", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("\\.", " ", tmp_baseline$common_name)

tmp_baseline <- tmp_baseline %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_baseline = n())%>% 
  pivot_wider(names_from = tmp, values_from = rich_baseline) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_baseline = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)



huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")

states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")


# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


# huc8 <- left_join(huc8, tmp_baseline, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_cc, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccdvlp, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccmgmt, by = "huc8_name")

huc12 <- left_join(huc12, tmp_baseline, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_sumtmp, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_BFI_HIST, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_LO7Q1DT_HIST, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_W95_HIST, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_BFIWs, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_WtDepWs, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_PctOw_Ws, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_PctImp_Ws, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_pctAg_Ws, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_pctWetland_Cat, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_logPctOw_Cat, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_logMJJA_HIST, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_logRdCrsCat, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_huc12_damden_sqkm, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_huc8_damcount, by = c("huc12_tnmid", "huc12_name"))



huc12 <- huc12 %>% 
  mutate(change_sumtmp = prop_cold_sumtmp - prop_cold_baseline,
         change_BFI_HIST = prop_cold_BFI_HIST - prop_cold_baseline,
         change_LO7Q1DT_HIST = prop_cold_LO7Q1DT_HIST - prop_cold_baseline,
         change_W95_HIST = prop_cold_W95_HIST - prop_cold_baseline,
         change_BFIWs = prop_cold_BFIWs - prop_cold_baseline,
         change_WtDepWs = prop_cold_WtDepWs - prop_cold_baseline,
         change_PctOw_Ws = prop_cold_PctOw_Ws - prop_cold_baseline,
         change_PctImp_Ws = prop_cold_PctImp_Ws - prop_cold_baseline,
         change_pctAg_Ws = prop_cold_pctAg_Ws - prop_cold_baseline,
         change_pctWetland_Cat = prop_cold_pctWetland_Cat - prop_cold_baseline,
         change_logPctOw_Cat = prop_cold_logPctOw_Cat - prop_cold_baseline,
         change_logMJJA_HIST = prop_cold_logMJJA_HIST - prop_cold_baseline,
         change_logRdCrsCat = prop_cold_logRdCrsCat - prop_cold_baseline,
         change_huc12_damden_sqkm = prop_cold_huc12_damden_sqkm - prop_cold_baseline,
         change_huc8_damcount = prop_cold_huc8_damcount - prop_cold_baseline
         )

#plot absolute values of proportion of cold spp richness
huc12a <- huc12 %>% 
  select(3:19) %>% 
  pivot_longer(2:17, names_to = "scenario", values_to = "prop_richness") %>% 
  filter(!is.na(prop_richness))
huc12a$scenario[huc12a$scenario == "prop_cold_baseline"] <- "Baseline"
huc12a$scenario[huc12a$scenario == "prop_cold_sumtmp"] <- "sumtmp"
huc12a$scenario[huc12a$scenario == "prop_cold_BFI_HIST"] <- "BFI_HIST"
huc12a$scenario[huc12a$scenario == "prop_cold_LO7Q1DT_HIST"] <- "LO7Q1DT_HIST"


ggplot(data = huc12a)+
  geom_sf(aes(fill = prop_richness), color = NA)+
  scale_fill_viridis_c()+
  facet_wrap(~scenario, nrow = 3)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Cold Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_cold_spp_richness.png",
    plot = last_plot(),
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300
  )

#plot change of proportion of cold spp richness
huc12a <- huc12 %>% 
  select(3, 21:35) %>% 
  pivot_longer(2:16, names_to = "scenario", values_to = "change") %>% 
  filter(!is.na(change))
huc12a$scenario[huc12a$scenario == "change_BFI_HIST"] <- "BFI_HIST"
huc12a$scenario[huc12a$scenario == "change_LO7Q1DT_HIST"] <- "LO7Q1DT_HIST"


ggplot(data = huc12a)+
  geom_sf(aes(fill = change), color = NA)+
  scale_fill_viridis_c(option = "magma")+
  facet_wrap(~scenario, nrow = 3)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Cold Species Richness Change")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_cold_spp_richness.png",
    plot = last_plot(),
    width = 9,
    height = 12,
    units = "cm",
    dpi = 300
  )

```




multinomial logistic regression predictions

```{r}
library(foreign)
library(nnet)

#load prediction dataset
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")


#load and prep huc12

huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")


sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")

#load and prep huc8
# huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
# sf_use_s2(FALSE)
# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


#load states
states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

#need to scale the variables in NHDplusV2_NewEngCrop

test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)
test <- test[,c(7:8, 10:39)]
test <- data.frame(scale(test))
NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1, 5, 6)], test)

#load model
mdl <- readRDS(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/trait_temp.rds")







#prediction using baseline values:

tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>% 
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_baseline <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_baseline <- temptraits_baseline %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_baseline)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_baseline.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )



ggplot(data = temptraits_baseline, aes(x = huc12_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")

ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_baseline_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )









#prediction using climate change values values:
NHDplusV2_NewEngCrop_cc <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2
         )


tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>% 
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_cc <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_cc <- temptraits_cc %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_cc)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_cc, aes(x = huc12_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")

ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )










#prediction using climate change and development  values:

NHDplusV2_NewEngCrop_ccdvlp <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
         PctImp_Ws = PctImp_Ws + 2,
         pctAg_Ws = pctAg_Ws + 2,
         logRdCrsCat = logRdCrsCat + 2,
         huc12_damden_sqkm = huc12_damden_sqkm + 2,
         huc8_damcount = huc8_damcount + 2
         )


tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_ccdvlp, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_ccdvlp, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccdvlp <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccdvlp <- temptraits_ccdvlp %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccdvlp)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccdvlp, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )







#prediction using climate change and management values:

NHDplusV2_NewEngCrop_ccmgmt <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
         PctImp_Ws = PctImp_Ws - 2,
         pctAg_Ws = pctAg_Ws - 2,
         logRdCrsCat = logRdCrsCat - 2,
         huc12_damden_sqkm = huc12_damden_sqkm - 2,
         huc8_damcount = huc8_damcount - 2,
         
         )

tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_ccmgmt, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_ccmgmt, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccmgmt <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccmgmt <- temptraits_ccmgmt %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccmgmt)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccmgmt, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )




temptraits_baseline$scenario <- "Baseline"
temptraits_cc$scenario <- "CC"
temptraits_ccdvlp$scenario <- "CC + Develop"
temptraits_ccmgmt$scenario <- "CC + Manage"


tmp <- bind_rows(temptraits_baseline, temptraits_cc, temptraits_ccdvlp, temptraits_ccmgmt)
tmp <- tmp %>% 
  filter(huc12_name %in% c("Sudbury Reservoir-Sudbury River", "East Branch Saco River", "Buffalo Stream"))
tmp$huc12_name <- factor(tmp$huc12_name, levels = c("Sudbury Reservoir-Sudbury River", "East Branch Saco River", "Buffalo Stream"))
tmp$scenario <- factor(tmp$scenario, levels = c("Baseline", "CC", "CC + Develop", "CC + Manage"))

ggplot(data = tmp, aes(x = huc12_name, y = mean, color = scenario))+
  scale_color_manual(values = c("mediumpurple1", "darkgoldenrod1", "red3", "green4"))+
  geom_point(size = 2, position=position_dodge(width=0.5))+
  geom_errorbar(aes(ymin = min, ymax = max), width = .5, position=position_dodge(width=0.5))+
  geom_hline(yintercept = 0.5, color = "grey80", linetype = "dashed")+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"))+
  labs(y = "Avg Proportional Abundance")+
  scale_y_continuous(limits = c(0, 1), breaks = 0.5)
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_compare_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )









diff <- temptraits_baseline %>% 
  rename(baseline_mean = mean) %>% 
  mutate(cc_mean = temptraits_cc$mean,
         ccdvlp_mean = temptraits_ccdvlp$mean,
         ccmgmt_mean = temptraits_ccmgmt$mean,
         change_dvlp = ccdvlp_mean - cc_mean,
         change_mgmt = ccmgmt_mean - cc_mean)


ggplot(data = diff)+
  geom_sf(aes(fill = change_dvlp), color = NA)+
  scale_fill_viridis_c(option = "magma", limits = c(-.25, 0.25))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Change")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_dvlp_change.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = diff)+
  geom_sf(aes(fill = change_mgmt), color = NA)+
  scale_fill_viridis_c(option = "magma", limits = c(-.25, 0.25))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Change")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_mmgt_change.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )


```