---
title: "Biodiversity Model Prediction"
author: "Jenny Rogers"
date: "2022-12-07"
output: html_document
---



```{r}

library(tidyverse)
library(sf)
library(glmmTMB)
library(readxl)



```

proportional abundance and probabilty of zero predictions
```{r}

load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")

#need to scale the variables
test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)

test <- test[,c(7:8, 10:42)]

#we need to scale these variables, but first I will calculate the mean and sd of each column, bc we will need to use these values to scale these variables in the predicted scenarios

means <- sapply(test, mean, na.rm = T)
save(means, file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fishcovariates_scaling_mean.RData")
sd <- sapply(test, sd, na.rm = T)
save(sd, file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fishcovariates_scaling_sd.RData")

#scale data
test <- data.frame(scale(test))

NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1:6, 9)], test)



#watershed shape files
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")
huc12 <- huc12 %>% 
  select(name, tnmid)


#fish traits
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_traits.RData")
temperature <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 1,
                  range = cell_cols("A:G")) %>% 
  pivot_longer(2:7, names_to = "state", values_to = "tmp") %>% 
  filter(!is.na(tmp),
         !tmp == "eury",
         !(common_name %in% c("american brook lamprey") & tmp == "cold"),
         !(common_name %in% c("common shiner", "white sucker", "smallmouth bass", "fallfish") & tmp == "warm")) %>% 
  select(-state) %>% 
  unique()

origin <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 2,
                  range = cell_cols("A:G"))%>% 
  pivot_longer(2:7, names_to = "state", values_to = "origin") %>% 
  filter(!is.na(origin),
         !(common_name == "spottail shiner" & origin == "introduced"),
         !origin == "unk") %>% 
  select(-state) %>%  
  unique()

#load fish clusters
geogclust <- read.csv("tmpfigures/fishclusters_bygeography.csv")
geogclust <- geogclust %>% 
  select(-1) %>% 
  rename(geogclust = final.cluster)
climclust <- read.csv("tmpfigures/fishclusters_byclimate.csv")
climclust <- climclust %>% 
  select(-1) %>% 
  rename(climclust = final.cluster)
tempclust <- read.csv("tmpfigures/fishclusters_bytemperature.csv")
tempclust <- tempclust %>% 
  select(-1) %>% 
  rename(tempclust = final.cluster)
flowclust <- read.csv("tmpfigures/fishclusters_bystreamflow.csv")
flowclust <- flowclust %>% 
  select(-1) %>% 
  rename(flowclust = final.cluster)

#proportional abundance predictions

file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "^propabun_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
names(predictions)[1] <- file.list[i]


for (i in 2:53) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
    tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions <- cbind(predictions, tmp)
  

  
}


#join the predictions to the list of comids
NHDplusV2_NewEngCrop_baseline <- cbind(NHDplusV2_NewEngCrop, predictions)


ggplot(data = NHDplusV2_NewEngCrop_baseline)+
  geom_sf(aes(color = propabun_fallfish.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#align prediction results with the unscaled covariates and make plots
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")
pred <- cbind(NHDplusV2_NewEngCrop, predictions)
pred <- pred %>%
  data.frame %>% 
  pivot_longer(43:95, values_to = "propabun", names_to = "common_name") 
pred$common_name <- gsub("propabun_", "", pred$common_name)
pred$common_name <- gsub(".rds", "", pred$common_name)
pred$common_name <- gsub("\\.", " ", pred$common_name)


#join to trait data and clusters so we can filter for certain temperature groups or origin
pred <- pred %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(geogclust, by = "common_name") %>% 
  left_join(climclust, by = "common_name") %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(flowclust, by = "common_name") %>% 
  left_join(tempclust, by = "common_name")

#write csv with final spp groupings
sppgroups <- pred %>% 
  select(common_name, tmp, tolerance, tempclust, flowclust, origin) %>% 
  unique() %>% 
  arrange(tmp, tolerance, tempclust, flowclust, origin)
sppgroups$origin[sppgroups$origin == "introduced"] <- "I"
sppgroups$origin[sppgroups$origin == "native"] <- "N"
sppgroups$tolerance[sppgroups$tolerance == "fluvial specialist"] <- "FS"
sppgroups$tolerance[sppgroups$tolerance == "fluvial dependent"] <- "FD"
sppgroups$tolerance[sppgroups$tolerance == "generalist"] <- "MG"
#add in scienfific names
names <- read_excel("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/fishspp_lookup_rq_comments.xlsx") %>% 
  select(scientific_name, common_name) 
sppgroups <- left_join(sppgroups, names, by = "common_name")%>% 
  select(common_name, scientific_name, tmp, tolerance, tempclust, flowclust, origin)
sppgroups$common_name <- str_to_title(sppgroups$common_name)
sppgroups$scientific_name <- str_to_sentence(sppgroups$scientific_name)
write.csv(sppgroups, "tmpfigures/paper1/sppgroups.csv")




#ratio of native to non-native species
OR <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, origin, propabun) %>% 
  unique() %>% 
  filter(!is.na(origin),
         propabun> 0.01) %>% 
  group_by(COMID, huc12_name, huc12_tnmid, origin) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  pivot_wider(values_from = propabun, names_from = origin) %>% 
  mutate(NatIntRatio = native/introduced) %>% 
  group_by(huc12_name, huc12_tnmid) %>%
  summarise(NatIntRatio = mean(NatIntRatio, na.rm = T))
OR <- left_join(huc12, OR, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(NatIntRatio))
 
aa <- ggplot(data = OR)+
  geom_sf(aes(fill = NatIntRatio), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = 50,
                       limits = c(1,100), 
                       breaks = c(1,100))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.position = c(0.78, 0.21),
        legend.key.size = unit(.25, "cm"),
        title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("D) Native to Introduced")+
  labs(fill = "Ratio")

ggsave(aa, file = "tmpfigures/paper1/NatIntRatio.png", 
    width = 18,
    height = 15,
    units = "cm",
    dpi = 300)


#ratio of specialist to generalist species
SP <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tolerance, propabun) %>% 
  unique() %>% 
  filter(!is.na(tolerance),
         propabun> 0.001,
         tolerance %in% c("fluvial specialist", "generalist")) %>% 
  group_by(COMID, huc12_name, huc12_tnmid, tolerance) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  pivot_wider(values_from = propabun, names_from = tolerance) %>% 
  mutate(speGenRatio = `fluvial specialist`/generalist) %>% 
  group_by(huc12_name, huc12_tnmid) %>%
  summarise(speGenRatio = mean(speGenRatio, na.rm = T))
SP <- left_join(huc12, SP, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(speGenRatio))
 
bb <- ggplot(data = SP)+
  geom_sf(aes(fill = speGenRatio), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = 330,
                       limits = c(0,665), 
                       breaks = c(0,665))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank())+
  ggtitle("B) Specialist to Generalist")+
  labs(fill = "Ratio")

ggsave(bb, file = "tmpfigures/paper1/SpeGenRatio.png", 
    width = 18,
    height = 15,
    units = "cm",
    dpi = 300)

fig4 <- gridExtra::grid.arrange(aa,bb, nrow = 1, ncol = 2)
ggsave(fig4, file = "tmpfigures/paper1/fig4.png")




#Temperature Clusters
TC <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tempclust, propabun) %>% 
  unique() %>% 
  filter(!is.na(tempclust),
         common_name != "brook trout") %>% 
  group_by(COMID, huc12_name, huc12_tnmid, tempclust) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(huc12_name, huc12_tnmid, tempclust) %>%
  summarise(propabun = mean(propabun, na.rm = T))
TC <- left_join(huc12, TC, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(tempclust))
TC$propabun <- ifelse(TC$propabun > 1, 1, TC$propabun)  
TC$tempclust[TC$tempclust == "1"] <- "1-cold, mid elev"
TC$tempclust[TC$tempclust == "2"] <- "2-warm, sm sheds"
TC$tempclust[TC$tempclust == "3"] <- "3-cool, low elev"
TC$tempclust[TC$tempclust == "4"] <- "4-cool, mid elev"
TC$tempclust[TC$tempclust == "5"] <- "5-cold, high elev"
TC$tempclust[TC$tempclust == "6"] <- "6-warm, lg sheds"

a <- ggplot(data = TC)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
  facet_wrap(~tempclust)+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.position = c(0.94, 0.10),
        legend.key.size = unit(.2, "cm"))+
  ggtitle("A) Temperature Clusters")+
  labs(fill = "P.Abun.")

ggsave(a, file = "tmpfigures/paper1/TempClusters.png", 
    width = 18,
    height = 15,
    units = "cm",
    dpi = 300)

#streamflow Clusters
FC <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, flowclust, propabun) %>% 
  unique() %>% 
  filter(!is.na(flowclust),
         common_name != "brook trout") %>% 
  group_by(COMID, huc12_name, huc12_tnmid, flowclust) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(huc12_name, huc12_tnmid, flowclust) %>%
  summarise(propabun = mean(propabun, na.rm = T))
FC <- left_join(huc12, FC, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(flowclust))
FC$propabun <- ifelse(FC$propabun > 1, 1, FC$propabun)
FC$flowclust[FC$flowclust == "1"] <- "1-Hi flood, Med Q"
FC$flowclust[FC$flowclust == "2"] <- "2-Mod flood, Lo Q"
FC$flowclust[FC$flowclust == "3"] <- "3-Hi flood, Low Q"
FC$flowclust[FC$flowclust == "4"] <- "4-Mod flood, Med Q"
FC$flowclust[FC$flowclust == "5"] <- "5-Hi flood, Hi Q"
FC$flowclust[FC$flowclust == "6"] <- "6-Lo flood, Med Q"

b <- ggplot(data = FC)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
  facet_wrap(~flowclust, nrow = 2)+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.position = c(0.94, 0.10),
        legend.key.size = unit(.2, "cm"),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("B) Streamflow Clusters")+
  labs(fill = "P.Abun.")

ggsave(b, file = "tmpfigures/paper1/FlowClusters.png", 
    width = 18,
    height = 15,
    units = "cm",
    dpi = 300)


fig7 <- gridExtra::grid.arrange(a,b, nrow = 1, ncol = 2)
ggsave(fig7, file = "tmpfigures/paper1/fig7.png")


#Temperature Guilds
TA <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tmp, propabun) %>% 
  unique() %>% 
  filter(!is.na(tmp),
         common_name != "brook trout") %>% 
  group_by(COMID, huc12_name, huc12_tnmid, tmp) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(huc12_name, huc12_tnmid, tmp) %>%
  summarise(propabun = mean(propabun, na.rm = T))
TA <- left_join(huc12, TA, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(tmp))
TA$propabun <- ifelse(TA$propabun > 1, 1, TA$propabun) 
TA$tmp <- str_to_title(TA$tmp)


c <- ggplot(data = TA)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
  facet_wrap(~tmp)+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        legend.text = element_text(size = 5),
        strip.text = element_text(size = 8),
        title = element_text(size = 10),
        legend.position = c(0.93, 0.25),
        legend.key.size = unit(.25, "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("A) Temperature Guilds")+
  labs(fill = NULL)

ggsave(c, file = "tmpfigures/paper1/TempGuilds.png", 
    width = 18,
    height = 10,
    units = "cm",
    dpi = 300)

#Fluvial guilds
pred$tolerance[pred$tolerance == "generalist"] <- "Macrohab. Generalist"
FA <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tolerance, propabun) %>% 
  unique() %>% 
  filter(!is.na(tolerance),
         common_name != "brook trout") %>% 
  group_by(COMID, huc12_name, huc12_tnmid, tolerance) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(huc12_name, huc12_tnmid, tolerance) %>%
  summarise(propabun = mean(propabun, na.rm = T))
FA <- left_join(huc12, FA, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(tolerance))
FA$propabun <- ifelse(FA$propabun > 1, 1, FA$propabun) 
FA$tolerance <- str_to_title(FA$tolerance)


d <- ggplot(data = FA)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
  facet_wrap(~tolerance)+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        legend.text = element_text(size = 5),
        strip.text = element_text(size = 8),
        legend.position = c(0.93, 0.25),
        legend.key.size = unit(.25, "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        title = element_text(size = 10),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("B) Habitat Guilds")+
  labs(fill = NULL)

ggsave(d, file = "tmpfigures/paper1/FlowGuilds.png", 
    width = 18,
    height = 10,
    units = "cm",
    dpi = 300)

#Origin groups
OG <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, origin, propabun) %>% 
  unique() %>% 
  filter(!is.na(origin),
         common_name != "brook trout") %>% 
  group_by(COMID, huc12_name, huc12_tnmid, origin) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(huc12_name, huc12_tnmid, origin) %>%
  summarise(propabun = mean(propabun, na.rm = T))
OG <- left_join(huc12, OG, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid")) %>% 
  filter(!is.na(origin))
OG$propabun <- ifelse(OG$propabun > 1, 1, OG$propabun) 
OG$origin <- str_to_title(OG$origin)



OG2 <- ggplot(data = OG)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
  facet_wrap(~origin)+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        legend.text = element_text(size = 5),
        strip.text = element_text(size = 8),
        legend.position = c(0.90, 0.25),
        legend.key.size = unit(.25, "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        title = element_text(size = 10),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("D) Origin Groups")+
  labs(fill = NULL)



#Brook Trout
BT <- pred %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, propabun) %>% 
  unique() %>% 
  filter(common_name == "brook trout") %>%
  group_by(huc12_name, huc12_tnmid) %>%
  summarise(propabun = mean(propabun, na.rm = T))
BT <- left_join(huc12, BT, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
BT$propabun <- ifelse(BT$propabun > 1, 1, BT$propabun)  


e <- ggplot(data = BT)+
  geom_sf(aes(fill = propabun), color = NA)+
  scale_fill_gradient2(low = "yellow",
                        mid = "orange",
                        high = "blue",
                        midpoint = .5,
                       limits = c(0,1), 
                       breaks = c(0,1))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        title = element_text(size = 10),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))+
  ggtitle("C) Brook Trout")+
  labs(fill = "Prop. Abun.")
  

ggsave(e, file = "tmpfigures/paper1/BrookTrout.png", 
    width = 8,
    height = 7,
    units = "cm",
    dpi = 300)

#add a locational map of new england in the uS for figure 2 in paper 1
#watershed shape files
huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
#load new england state data
states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")
#load USA states
US <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/USstates/cb_2018_us_state_5m.shp")
US <- US %>% 
  filter(STUSPS %in% c("ME", "NH", "VT", "MA", "CT", "RI", "NY", "PA", "NJ", "MD", "VA", "OH", "WV", "DE"))
st_crs(huc8) == st_crs(US)
states <- st_transform(states, crs = st_crs(huc8))
st_crs(huc8) == st_crs(states)


locationalMap <- ggplot(data = US)+
  geom_sf(color = "black", fill = "grey90")+
  geom_sf(data = states, fill = "red2")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 7),
        legend.position = "none",
        title = element_text(size = 10))+
  ggtitle("E) Study Location")


fig2 <- gridExtra::grid.arrange(arrangeGrob(c,d, ncol = 2),
                                arrangeGrob(e, OG2, locationalMap, ncol = 3))
ggsave(fig2, file = "tmpfigures/paper1/fig2.png", width = 18, height = 12, units = "cm")


#plot each variable calcuated above against all the others in the ggpairs plot
TC <- TC %>% 
  data.frame() %>% 
  select(name, tnmid, tempclust, propabun)  %>%
  unique() %>% 
  pivot_wider(names_from = tempclust, values_from = propabun) %>% 
  rename(Tempclust_1 = "1-cold, mid elev", Tempclust_2 = "2-warm, sm sheds", Tempclust_3 = "3-cool, low elev", 
         Tempclust_4 = "4-cool, mid elev", Tempclust_5 = "5-cold, high elev", Tempclust_6 = "6-warm, lg sheds")

FC <- FC %>% 
  data.frame() %>% 
  select(name, tnmid, flowclust, propabun)  %>%
  unique() %>% 
  pivot_wider(names_from = flowclust, values_from = propabun) %>% 
  rename(Flowclust_1 = "1-Hi flood, Med Q", Flowclust_2 = "2-Mod flood, Lo Q", Flowclust_3 = "3-Hi flood, Low Q", 
         Flowclust_4 = "4-Mod flood, Med Q", Flowclust_5 = "5-Hi flood, Hi Q", Flowclust_6 = "6-Lo flood, Med Q")

TA <- TA %>% 
  data.frame() %>% 
  select(name, tnmid, tmp, propabun)  %>%
  unique() %>% 
  pivot_wider(names_from = tmp, values_from = propabun) 

FA <- FA %>% 
  data.frame() %>% 
  select(name, tnmid, tolerance, propabun)  %>%
  unique() %>% 
  pivot_wider(names_from = tolerance, values_from = propabun)

BT <- BT %>% 
  data.frame() %>%
  select(name, tnmid, propabun)  %>%
  unique() %>% 
  filter(!is.na(propabun)) %>% 
  rename("Brook Trout" = propabun)

OR <- OR %>% 
  data.frame() %>% 
  select(name, tnmid, NatIntRatio) %>% 
  unique() %>% 
  filter(!is.na(NatIntRatio))

OG <- OG %>% 
  data.frame() %>% 
  select(name, tnmid, origin, propabun) %>% 
  unique() %>% 
  pivot_wider(names_from = origin, values_from = propabun)

SP <- SP %>% 
  data.frame() %>% 
  select(name, tnmid, speGenRatio) %>% 
  unique() %>% 
  filter(!is.na(speGenRatio))

compare <- left_join(TC, FC, by = c("name", "tnmid")) %>% 
  left_join(TA, by = c("name", "tnmid")) %>% 
  left_join(FA, by = c("name", "tnmid")) %>% 
  left_join(BT, by = c("name", "tnmid")) %>%
  left_join(OG, by = c("name", "tnmid")) %>%  
  select(-name, -tnmid)
  
compare <- compare[complete.cases(compare),]

library(GGally)
ggpairs(compare)
names(compare)

names(compare)[names(compare) == "Macrohab. Generalist"] <-  "Macrohabitat Generalist"
test <- cor(compare)
test <- test %>% 
  data.frame() %>% 
  select(13:21) %>% 
  filter(rownames(test) %in% c("Tempclust_1", "Tempclust_2", "Tempclust_3", "Tempclust_4", 
                               "Tempclust_5", "Tempclust_6", "Flowclust_1", "Flowclust_2", 
                               "Flowclust_3", "Flowclust_4", "Flowclust_5", "Flowclust_6")) %>%
  rename("Fluvial Specialist"="Fluvial.Specialist",  "Fluvial Dependent" = "Fluvial.Dependent", "Brook Trout" = "Brook.Trout",
         "Macrohabitat Generalist" = "Macrohabitat.Generalist") %>% 
  as.matrix()

library(corrplot)
png(file = "tmpfigures/paper1/correlationmatrix.png", res = 200, width = 10, height = 15, units = "in", pointsize = 24)
corrplot(test, method = "square", outline = T, addgrid.col = "darkgray", 
         addCoef.col = "white", number.digits = 2, number.cex = 0.9, tl.col = "black")
dev.off()

write.csv(test, file = "tmpfigures/paper1/correlationmatrix.csv")






#make violin plots with the distrubiton of each trait by lat and long
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDv2_huc_state_join.RData")

#join the predictions_zero to the list of comids
NHDplusV2_NewEngCrop <- NHDplusV2_NewEngCrop %>% 
  select(COMID)
bylat <- cbind(NHDplusV2_NewEngCrop, predictions) 
bylat <- data.frame(bylat) %>% 
  select(-geometry) %>% 
  pivot_longer(2:54, values_to = "propabun", names_to = "common_name") 
bylat$common_name <- gsub("propabun_", "", pred$common_name)
bylat$common_name <- gsub(".rds", "", pred$common_name)
bylat$common_name <- gsub("\\.", " ", pred$common_name)


#join to trait data and clusters so we can filter for certain temperature groups or origin
bylat <- bylat %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(geogclust, by = "common_name") %>% 
  left_join(climclust, by = "common_name") %>% 
  left_join(final_traits, by = "common_name")%>% 
  left_join(flowclust, by = "common_name") %>% 
  left_join(tempclust, by = "common_name")

bylat <- left_join(NHDv2_huc_state_join, bylat, by = "COMID")

df1 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, tmp) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = tmp)
df2 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, tolerance) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = tolerance)
df3 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, tempclust) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = tempclust) %>% 
  mutate(trait = as.character(trait) ) %>% 
  filter(!is.na(trait))
df3$trait <- paste("TC", df3$trait, sep = "_")
df4 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, flowclust) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = flowclust) %>% 
  mutate(trait = as.character(trait) )%>% 
  filter(!is.na(trait))
df4$trait <- paste("FC", df4$trait, sep = "_")

df5 <- bylat %>% 
  data.frame() %>% 
  filter(common_name == "brook trout") %>% 
  select(COMID, common_name, propabun) %>% 
  rename(trait = common_name)
df6 <- bylat %>% 
  data.frame() %>% 
  select(COMID, common_name, origin, propabun) %>% 
  group_by(COMID, origin) %>% 
  summarise(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = origin) %>% 
  filter(!is.na(trait))


latlong <- NHDv2_huc_state_join %>%
  data.frame() %>% 
  select(COMID, lat, long) %>% 
  unique()
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")
elev <- NHDplusV2_NewEngCrop %>% 
  select(COMID, ElevCat)

df7 <- rbind(df1, df2, df3, df4, df5, df6)
df7 <- left_join(df7, latlong, by = "COMID") %>% 
  left_join(elev, by = "COMID") %>% 
  filter(!is.na(trait),
         !is.na(ElevCat)) %>% 
  mutate(latitude  = ifelse(lat > 44.51944, "High latitude",
                            ifelse(lat < 42.97004, "Low latitude", "Mid latitude"))) %>% 
  mutate(elevation  = ifelse(ElevCat > 181.4322 , "High elevation", "Low elevation")) %>% 
  mutate(longitude  = ifelse(long > -71.27307, "East", "West")) %>% 
  filter(propabun < 1.2)

df7$latitude <- factor(df7$latitude, levels = c("Low latitude", "Mid latitude", "High latitude"))
df7$elevation <- factor(df7$elevation, levels = c("Low elevation", "Mid elevation", "High elevation"))

df8 <- df7 %>% 
  filter(trait %in% c("TC_1", "TC_2", "TC_3", "TC_4", "TC_5", "TC_6", 
                      "FC_1", "FC_2", "FC_3", "FC_4", "FC_5", "FC_6"))

df9 <- df7 %>% 
  filter(trait %in% c("cold", "cool", "warm", "fluvial specialist", "fluvial dependent", "generalist", 
                      "brook trout","native", "introduced" ))
df9$trait[df9$trait == "native"] <- "Native"
df9$trait[df9$trait == "introduced"] <- "Introduced"
df9$trait[df9$trait == "generalist"] <- "Macrohabitat Generalist"

ggplot(data = df8, mapping = aes(x = trait, y = propabun))+
  geom_boxplot(outlier.size = .5, outlier.colour = "grey80")+ 
  facet_grid(rows = vars(elevation), cols = vars(latitude))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(x = "Grouping", y = "Average Proportional Abundance")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))+
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "red")+
  geom_hline(yintercept = 0.25, linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0.75, linetype = "dashed", color = "red")
ggsave(plot = last_plot(),
       file = "tmpfigures/paper1/clustersbylatlong.png", 
    width = 20,
    height = 12,
    units = "cm",
    dpi = 300)

df9$trait <- str_to_title(df9$trait)
df9$trait <- factor(df9$trait, levels = c("Cold", "Cool", "Warm", 
                                          "Fluvial Specialist", "Fluvial Dependent","Macrohabitat Generalist",
                                          "Brook Trout", "Native", "Introduced" ))

ggplot(data = df9, mapping = aes(x = trait, y = propabun))+
  geom_boxplot(outlier.size = .5, outlier.colour = "grey80")+
  facet_grid(rows = vars(elevation), cols = vars(latitude))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  labs(x = "Grouping", y = "Average Proportional Abundance")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))+
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0.25, linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0.75, linetype = "dashed", color = "red")
ggsave(plot = last_plot(),
       file = "tmpfigures/paper1/Metricbylatlong.png", 
    width = 20,
    height = 12,
    units = "cm",
    dpi = 300)


 
stats <- df8 %>% 
  data.frame() %>% 
  group_by(trait, latitude, elevation) %>% 
  summarise(mean = round(mean(propabun), 2)) %>% 
  filter(trait %in% c("FC_2"))







##################################################################################################

##################################################################################################

##################   probability of zero predictions   ###########################################

##################################################################################################

##################################################################################################







load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")

#need to scale the variables
test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)
test <- test[,c(7:8, 10:39)]

#scale data
test <- data.frame(scale(test))

NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1:6, 9)], test)


file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "propabun_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_zero <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "zprob"))
names(predictions_zero)[1] <- file.list[i]


for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
    tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "zprob"))
  names(tmp)[1] <- file.list[i]
  
  predictions_zero <- cbind(predictions_zero, tmp)
  

  
}

names(predictions_zero) <- gsub("propabun", "probZero", names(predictions_zero))

#join the predictions_zero to the list of comids
NHDplusV2_NewEngCrop_baseline <- cbind(NHDplusV2_NewEngCrop, predictions_zero)


ggplot(data = NHDplusV2_NewEngCrop_baseline)+
  geom_sf(aes(color = probZero_eastern.blacknose.dace.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)


#align prediction results with the unscaled covariates and make plots
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")
pred_zero <- cbind(NHDplusV2_NewEngCrop, predictions_zero)
pred_zero <- pred_zero %>%
  data.frame %>% 
  pivot_longer(40:96, values_to = "probZero", names_to = "common_name") 
pred_zero$common_name <- gsub("probZero_", "", pred_zero$common_name)
pred_zero$common_name <- gsub(".rds", "", pred_zero$common_name)
pred_zero$common_name <- gsub("\\.", " ", pred_zero$common_name)


#join to trait data so we can filter for certain temperature groups or origin
pred_zero <- pred_zero %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(geogclust, by = "common_name") %>% 
  left_join(climclust, by = "common_name") %>% 
  left_join(final_traits, by = "common_name")

#write csv with final spp groupings
sppgroups <- pred_zero %>% 
  select(common_name, tmp, tolerance, climclust) %>% 
  unique() %>% 
  arrange(tmp)
write.csv(sppgroups, "tmpfigures/paper1/sppgroups.csv")


#plot cold water native species richness
coldnat <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tmp, origin, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>% 
  unique() %>% 
  filter(tmp == "cold") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(coldnatrich = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(coldnatrich = mean(coldnatrich))
coldnat <- left_join(huc12, coldnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))

cldnrich <- ggplot(data = coldnat)+
  geom_sf(aes(fill = coldnatrich), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 1.5,
                       limits = c(0,3),
                       breaks = c(0,3))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
  ggtitle("richness")+
    geom_text(label = "Cold",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot cool water native species richness
coolnat <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tmp, origin, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>% 
  unique() %>% 
  filter(tmp == "cool") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(coolnatrich = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(coolnatrich = mean(coolnatrich))
coolnat <- left_join(huc12, coolnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
coolnrich <- ggplot(data = coolnat)+
  geom_sf(aes(fill = coolnatrich), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 3,
                       limits = c(0,6),
                       breaks = c(0,6))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "Cool",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot warm water native species richness
warmnat <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tmp, origin, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(tmp == "warm") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(warmnatrich = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(warmnatrich = mean(warmnatrich))
warmnat <- left_join(huc12, warmnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
wnrich <- ggplot(data = warmnat)+
  geom_sf(aes(fill = warmnatrich), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 3,
                       limits = c(0,6),
                       breaks = c(0,6))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "Warm",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot warm water nonnative species richness
# warmnonnat <- pred_zero %>% 
#   select(COMID, huc12_name, huc12_tnmid, common_name, tmp, origin, probZero)  %>% 
#   mutate(probOcc = 1 - probZero) %>%   
#   unique() %>% 
#   filter(tmp == "warm" & origin == "introduced") %>%
#   group_by(COMID, huc12_name, huc12_tnmid) %>% 
#   summarise(warmnonnatrich = sum(probOcc, na.rm = T)) %>% 
#   group_by(huc12_name, huc12_tnmid) %>% 
#   summarise(warmnonnatrich = mean(warmnonnatrich))
# warmnonnat <- left_join(huc12, warmnonnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
# wnnrich <- ggplot(data = warmnonnat)+
#   geom_sf(aes(fill = warmnonnatrich), color = NA)+
#   scale_fill_gradient2(low = "grey60",
#                         mid = "yellow",
#                         high = "green3",
#                         midpoint = 3.06,
#                        limits = c(0,6.2),
#                        breaks = c(0,6))+
#     theme(panel.border = element_rect(colour = "black", fill = NA),
#           panel.grid.major = element_blank(),
#           panel.grid.minor = element_blank(),
#           panel.background = element_blank(),
#         axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         legend.text = element_text(size = 12),
#         legend.title = element_text(size = 15))+
#     geom_text(label = "WNN",x=-72.5,y=47, color = "black", size = 5)+
#   labs(fill = NULL)


#plot from geog clusters 
geog_rich1 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, geogclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(geogclust == 1) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich1 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich1 = mean(geog_rich1))
geog_rich1 <- left_join(huc12, geog_rich1, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
geog_1rich <- ggplot(data = geog_rich1)+
  geom_sf(aes(fill = geog_rich1), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = .3,
                       limits = c(0,.6),
                       breaks = c(0,.6))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
  ggtitle("richness")+
    geom_text(label = "geo 1",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from geog clusters 
geog_rich2 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, geogclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(geogclust == 2) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich2 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich2 = mean(geog_rich2))
geog_rich2 <- left_join(huc12, geog_rich2, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
geog_2rich <- ggplot(data = geog_rich2)+
  geom_sf(aes(fill = geog_rich2), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2.6,
                       limits = c(0,5.2),
                       breaks = c(0,5.2))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "geo 2",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from geog clusters 
geog_rich3 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, geogclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(geogclust == 3) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich3 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(geog_rich3 = mean(geog_rich3))
geog_rich_3 <- left_join(huc12, geog_rich3, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
geog_rich3 <- ggplot(data = geog_rich_3)+
  geom_sf(aes(fill = geog_rich3), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 4.25,
                       limits = c(0,8.5),
                       breaks = c(0, 8.5))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "geo 3",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)




#plot from fluvial dependence clusters 
specialist_rich1 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tolerance, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(tolerance == "fluvial specialist") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(specialist_rich1 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(specialist_rich1 = mean(specialist_rich1))
specialist_rich1 <- left_join(huc12, specialist_rich1, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
specialist_rich1 <- ggplot(data = specialist_rich1)+
  geom_sf(aes(fill = specialist_rich1), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 3,
                       limits = c(0,6),
                       breaks = c(0,6))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
  ggtitle("richness")+
    geom_text(label = "FS",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from geog clusters 
dependent_rich2 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tolerance, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(tolerance == "fluvial dependent") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(dependent_rich2 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(dependent_rich2 = mean(dependent_rich2))
dependent_rich2 <- left_join(huc12, dependent_rich2, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
dependent_2rich <- ggplot(data = dependent_rich2)+
  geom_sf(aes(fill = dependent_rich2), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 1,
                       limits = c(0,2),
                       breaks = c(0,2))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "FD",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from geog clusters 
generalist_rich3 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, tolerance, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(tolerance == "generalist") %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(generalist_rich3 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(generalist_rich3 = mean(generalist_rich3))
generalist_rich3 <- left_join(huc12, generalist_rich3, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
generalist_rich3 <- ggplot(data = generalist_rich3)+
  geom_sf(aes(fill = generalist_rich3), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2.5,
                       limits = c(0,5.1),
                       breaks = c(0, 5))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "Gen",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)


#plot from climate clusters 
clim_rich1 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 1) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich1 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich1 = mean(clim_rich1))
clim_rich1 <- left_join(huc12, clim_rich1, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich1 <- ggplot(data = clim_rich1)+
  geom_sf(aes(fill = clim_rich1), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2.25,
                       limits = c(0,4.5),
                       breaks = c(0, 4.5))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
  ggtitle("richness")+
    geom_text(label = "cli 1",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from climate clusters 
clim_rich2 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 2) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich2 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich2 = mean(clim_rich2))
clim_rich_2 <- left_join(huc12, clim_rich2, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich2 <- ggplot(data = clim_rich_2)+
  geom_sf(aes(fill = clim_rich2), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 1.75,
                       limits = c(0, 3.5),
                       breaks = c(0, 3.5))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "cli 2",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)


#plot from climate clusters 
clim_rich3 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 3) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich3 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich3 = mean(clim_rich3))
clim_rich_3 <- left_join(huc12, clim_rich3, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich3 <- ggplot(data = clim_rich_3)+
  geom_sf(aes(fill = clim_rich3), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2,
                       limits = c(0, 4),
                       breaks = c(0, 4))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "cli 3",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)


#plot from climate clusters 
clim_rich4 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 4) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich4 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich4 = mean(clim_rich4))
clim_rich4 <- left_join(huc12, clim_rich4, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich4 <- ggplot(data = clim_rich4)+
  geom_sf(aes(fill = clim_rich4), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2,
                       limits = c(0, 4),
                       breaks = c(0, 4))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "cli 4",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from climate clusters 
clim_rich5 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 5) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich5 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich5 = mean(clim_rich5))
clim_rich5 <- left_join(huc12, clim_rich5, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich5 <- ggplot(data = clim_rich5)+
  geom_sf(aes(fill = clim_rich5), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2,
                       limits = c(0, 4),
                       breaks = c(0, 4))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "cli 5",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)

#plot from climate clusters 
clim_rich6 <- pred_zero %>% 
  select(COMID, huc12_name, huc12_tnmid, common_name, climclust, probZero) %>% 
  mutate(probOcc = 1 - probZero) %>%  
  unique() %>% 
  filter(climclust == 6) %>%
  group_by(COMID, huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich6 = sum(probOcc, na.rm = T)) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(clim_rich6 = mean(clim_rich6))
clim_rich6 <- left_join(huc12, clim_rich6, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
clim_rich6 <- ggplot(data = clim_rich6)+
  geom_sf(aes(fill = clim_rich6), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = 2,
                       limits = c(0, 4),
                       breaks = c(0, 4))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "cli 6",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = NULL)






#plot probability of brook trout probZero
brktrt <- pred_zero %>% 
  select(huc12_name, huc12_tnmid, common_name, probZero) %>% 
  unique() %>% 
  filter(common_name == "brook trout",
         probZero < .9) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(brktrtprob = 1 - (mean(probZero)))
brktrt <- left_join(huc12, brktrt, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
brkrich <- ggplot(data = brktrt)+
  geom_sf(aes(fill = brktrtprob), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = .5,
                       limits = c(0,1))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "Brook Trout",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = "Prob")

#plot probability of pumpkinseed probZero
pumpkin <- pred_zero %>% 
  select(huc12_name, huc12_tnmid, common_name, probZero) %>% 
  unique() %>% 
  filter(common_name == "pumpkinseed",
         probZero < .99) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(pmkprob = 1 - (mean(probZero)))
pumpkin <- left_join(huc12, pumpkin, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
pmkrich <- ggplot(data = pumpkin)+
  geom_sf(aes(fill = pmkprob), color = NA)+
  scale_fill_gradient2(low = "grey60",
                        mid = "yellow",
                        high = "green3",
                        midpoint = .5,
                       limits = c(0,1))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15))+
    geom_text(label = "Pumpkinseed",x=-72.5,y=47, color = "black", size = 5)+
  labs(fill = "Prob")


c <- arrangeGrob(cldnprob, cldnrich, 
                 coolnprob, coolnrich, 
                 wnprob, wnrich,
             ncol=2, nrow =3)
ggsave(c, file = "tmpfigures/paper1/BaselineFishTempDist.png", 
    width = 12,
    height = 15,
    units = "cm",
    dpi = 300)



cc <- arrangeGrob(specprob_1, cldnprob, 
                 depprop_1, coolnprob, 
                 genprob_1, wnprob,
             ncol=2, nrow =3)
ggsave(cc, file = "tmpfigures/paper1/BaselineFishTmpTolerance.png", 
    width = 12,
    height = 15,
    units = "cm",
    dpi = 300)



d <- arrangeGrob(clim_1prob, 
                 clim_2prob, 
                 clim_3prob,
                 clim_4prob,
                 clim_5prob, 
                 clim_6prob,
             ncol=2, nrow =3)
ggsave(d, file = "tmpfigures/paper1/BaselineFishClimDist.png", 
    width = 12,
    height = 20,
    units = "cm",
    dpi = 100)

e <- arrangeGrob(geog_1prob, geog_1rich, 
                 geog_2prob, geog_2rich, 
                 geog_3prob, geog_rich3,
             ncol=2, nrow =3)
ggsave(e, file = "tmpfigures/BaselineFishGeoDist.png", 
    width = 12,
    height = 15,
    units = "cm",
    dpi = 300)




#plot each variable calcuated above against all the others in the ggpairs plot

compare <- data.frame(
  cold_pa = coldnat_1$coldnatpropabund,
  cool_pa = coolnat_1$coolnatpropabund,
  warm_pa = warmnat_1$warmnatpropabund,
  cold_ri = coldnat$coldnatrich,
  cool_ri = coolnat$coolnatrich,
  warm_ri = warmnat$warmnatrich,
  brktrt_pa = brktrt_1$brktrt_propabun,
  clim_1_pa = clim_1$clim_1,
  clim_2_pa = clim_2$clim_2,
  clim_3_pa = clim_3$clim_3,
  clim_4_pa = clim_4$clim_4,
  clim_5_pa = clim_5$clim_5,
  clim_6_pa = clim_6$clim_6,
  clim_1_ri = clim_rich1$clim_rich1,
  clim_2_ri = clim_rich_2$clim_rich2,
  clim_3_ri = clim_rich_3$clim_rich3,
  clim_4_ri = clim_rich4$clim_rich4,
  clim_5_ri = clim_rich5$clim_rich5,
  clim_6_ri = clim_rich6$clim_rich6,
  brktrt_ri = brktrt$brktrtprob,
  dependant_pa = dependant_1$deppropabund,
  generalist_pa = generalist_1$genpropabund,
  specialist_pa = specialist_1$spenatpropabund,
  dependant_ri = dependent_rich2$dependent_rich2,
  generalist_ri = generalist_rich3$generalist_rich3,
  specialist_ri = specialist_rich1$specialist_rich1,
  pmk_ri = pumpkin$pmkprob,
  pmk_pa = pumpkin_1$pmk_propabun
  
  
)


compare <- compare[complete.cases(compare),]

library(GGally)
ggpairs(compare)
names(compare)

test <- cor(compare)
test <- test %>% 
  data.frame() %>% 
  select(contains("pa") & !contains("clim")) %>% 
  filter(rownames(test) %in% c("clim_1_pa", "clim_2_pa", "clim_3_pa", "clim_4_pa", "clim_5_pa", "clim_6_pa"))
write.csv(test, file = "tmpfigures/paper1/correlationmatrix.csv")

cor.test(compare$cold_pa, compare$cold_ri, use = "complete.obs") #0.8708906
cor.test(compare$cool_pa, compare$cool_ri, use = "complete.obs") #0.9331168 
cor.test(compare$warm_pa, compare$warm_ri, use = "complete.obs") #0.9120983 
cor.test(compare$clim_1_pa, compare$clim_1_ri, use = "complete.obs") #0.9557679 
cor.test(compare$clim_2_pa, compare$clim_2_ri, use = "complete.obs") #0.9213403 
cor.test(compare$clim_3_pa, compare$clim_3_ri, use = "complete.obs") #0.905495 
cor.test(compare$clim_4_pa, compare$clim_4_ri, use = "complete.obs") #0.805493
cor.test(compare$clim_5_pa, compare$clim_5_ri, use = "complete.obs") #0.9370384
cor.test(compare$clim_6_pa, compare$clim_6_ri, use = "complete.obs") #0.9471381
cor.test(compare$dependant_pa, compare$dependant_ri, use = "complete.obs") #0.8623393
cor.test(compare$generalist_pa, compare$generalist_ri, use = "complete.obs") #0.924191 
cor.test(compare$specialist_pa, compare$specialist_ri, use = "complete.obs") #0.7481394
cor.test(compare$brktrt_pa, compare$brktrt_ri, use = "complete.obs") #0.8138806



#calcuate the percentage of each metric within each state
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDv2_huc_state_join.RData")

#join the predictions_zero to the list of comids
NHDplusV2_NewEngCrop <- NHDplusV2_NewEngCrop %>% 
  select(COMID)
bystate <- cbind(NHDplusV2_NewEngCrop, predictions_zero) 
bystate <- data.frame(bystate) %>% 
  select(-geometry) %>% 
  pivot_longer(2:58, values_to = "ZeroProb", names_to = "common_name") 
bystate$common_name <- gsub("probZero_", "", pred$common_name)
bystate$common_name <- gsub(".rds", "", pred$common_name)
bystate$common_name <- gsub("\\.", " ", pred$common_name)


#join to trait data and clusters so we can filter for certain temperature groups or origin
bystate <- bystate %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(geogclust, by = "common_name") %>% 
  left_join(climclust, by = "common_name") %>% 
  left_join(final_traits, by = "common_name")


bystate <- left_join(NHDv2_huc_state_join, bystate, by = "COMID")

#calcuate the average prob, total prob, and proportional probabilty of each temperature group across the states
temp <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(tmp)) %>% 
  select(COMID, state, tmp, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>% 
  group_by(tmp) %>% 
  summarise(prob = sum(probOcc, na.rm = T))

temp2 <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(tmp)) %>% 
  select(COMID, state, tmp, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>%
  group_by(COMID, state, tmp) %>% 
  summarise(total_prob = sum(probOcc, na.rm = T)) %>% 
  ungroup %>% 
  group_by(state, tmp) %>% 
  summarise(tmp_avg_prob = round(mean(total_prob, na.rm = T),2), #average prob zero within each COMID across the state
            tmp_total_prob = round(sum(total_prob, na.rm = T), 0)) %>% #total prob zero within each COMID across the state
  left_join(temp, by = "tmp") %>% 
  mutate(prop_prob = round(tmp_total_prob/prob , 2)) %>%  # proportional prob zero across the state
  select(-prob) %>% 
  pivot_longer(3:5, names_to = "variable", values_to = "value") %>% 
  filter(variable != "tmp_total_prob")

temp2$tmp <- factor(temp2$tmp, levels = c("cold", "cool", "warm"))
temp2$variable <- factor(temp2$variable, levels = c("tmp_avg_prob", "prop_prob"))


tmpbystate <- ggplot(data = temp2, mapping = aes(y = tolower(state), x = value, fill = tmp))+
  geom_bar(stat = "identity", position = "dodge", color = "black")+
  scale_fill_manual(values=c("royalblue3", "yellowgreen", "chocolate2"))+
  facet_wrap(~variable, scales = "free", labeller = as_labeller(c("prop_prob" = "Proportion", "tmp_avg_prob" = "Average")))+
  labs(x = NULL, y = NULL)+
  theme(strip.text = element_text(size = 12, color = "black"),
        strip.background = element_rect(color = "black", fill = "grey80", linewidth = 1.5))
ggsave(tmpbystate, file = "tmpfigures/paper1/tempbystate.png", 
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300)


#calcuate the average prob, total prob, and proportional probabilty of each tolerance group across the states
tol <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(tolerance)) %>% 
  select(COMID, state, tolerance, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>% 
  group_by(tolerance) %>% 
  summarise(prob = sum(probOcc, na.rm = T))

tol2 <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(tolerance)) %>% 
  select(COMID, state, tolerance, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>%
  group_by(COMID, state, tolerance) %>% 
  summarise(total_prob = sum(probOcc, na.rm = T)) %>% 
  ungroup %>% 
  group_by(state, tolerance) %>% 
  summarise(tol_avg_prob = round(mean(total_prob, na.rm = T),2), #average prob zero within each COMID across the state
            tol_total_prob = round(sum(total_prob, na.rm = T), 0)) %>% #total prob zero within each COMID across the state
  left_join(tol, by = "tolerance") %>% 
  mutate(prop_prob = round(tol_total_prob/prob , 2)) %>%  # proportional prob zero across the state
  select(-prob) %>% 
  pivot_longer(3:5, names_to = "variable", values_to = "value") %>% 
  filter(variable != "tol_total_prob")

tol2$tolerance <- factor(tol2$tolerance, levels = c("fluvial specialist", "fluvial dependent", "generalist"))
tol2$variable <- factor(tol2$variable, levels = c("tol_avg_prob", "prop_prob"))

tolbystate <- ggplot(data = tol2, mapping = aes(y = tolower(state), x = value, fill = tolerance))+
  geom_bar(stat = "identity", position = "dodge", color = "black")+
  scale_fill_manual(values=c("royalblue3", "yellowgreen", "chocolate2"))+
  facet_wrap(~variable, scales = "free", labeller = as_labeller(c("prop_prob" = "Proportion", "tol_avg_prob" = "Average")))+
  labs(x = NULL, y = NULL)+
  theme(strip.text = element_text(size = 12, color = "black"),
        strip.background = element_rect(color = "black", fill = "grey80", linewidth = 1.5))
ggsave(tolbystate, file = "tmpfigures/paper1/tolbystate.png", 
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300)



  #calcuate the average prob, total prob, and proportional probabilty of each cluster group across the states
clust <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(climclust)) %>% 
  select(COMID, state, climclust, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>% 
  group_by(climclust) %>% 
  summarise(prob = sum(probOcc, na.rm = T))

clust2 <- bystate %>% 
  data.frame() %>% 
  filter(!is.na(climclust)) %>% 
  select(COMID, state, climclust, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>%
  group_by(COMID, state, climclust) %>% 
  summarise(total_prob = sum(probOcc, na.rm = T)) %>% 
  ungroup %>% 
  group_by(state, climclust) %>% 
  summarise(clu_avg_prob = round(mean(total_prob, na.rm = T),2), #average prob zero within each COMID across the state
            clu_total_prob = round(sum(total_prob, na.rm = T), 0)) %>% #total prob zero within each COMID across the state
  left_join(clust, by = "climclust") %>% 
  mutate(prop_prob = round(clu_total_prob/prob , 2)) %>%  # proportional prob zero across the state
  select(-prob) %>% 
  pivot_longer(3:5, names_to = "variable", values_to = "value") %>% 
  filter(variable != "clu_total_prob")

clust2$climclust <- factor(clust2$climclust, levels = c(4, 3, 2, 1))
clust2$variable <- factor(clust2$variable, levels = c("clu_avg_prob", "prop_prob"))

clubystate <- ggplot(data = clust2, mapping = aes(y = tolower(state), x = value, fill = as.factor(climclust)))+
  geom_bar(stat = "identity", position = "dodge", color = "black")+
  scale_fill_manual(values=c("royalblue3","orchid3" , "yellowgreen", "chocolate2"))+
  facet_wrap(~variable, scales = "free", labeller = as_labeller(c("prop_prob" = "Proportion", "clu_avg_prob" = "Average")))+
  labs(x = NULL, y = NULL, fill = "cluster")+
  theme(strip.text = element_text(size = 12, color = "black"),
        strip.background = element_rect(color = "black", fill = "grey80", linewidth = 1.5))
ggsave(clubystate, file = "tmpfigures/paper1/clubystate.png", 
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300)



  #calcuate the average prob, total prob, and proportional probabilty of brook trout across the states
spp <- bystate %>% 
  data.frame() %>% 
  filter(common_name %in% c("brook trout", "pumpkinseed", "common shiner")) %>% 
  filter(!is.na(ZeroProb)) %>% 
  select(COMID, state, common_name, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>% 
  group_by(common_name) %>% 
  summarise(prob = sum(probOcc, na.rm = T))

spp2 <- bystate %>% 
  data.frame() %>% 
  filter(common_name %in% c("brook trout", "pumpkinseed", "common shiner")) %>% 
  filter(!is.na(ZeroProb)) %>% 
  select(COMID, state, common_name, ZeroProb) %>% 
  mutate(probOcc = 1 - ZeroProb) %>% 
  unique() %>%
  group_by(COMID, state, common_name) %>% 
  summarise(total_prob = sum(probOcc, na.rm = T)) %>% 
  ungroup %>% 
  group_by(state, common_name) %>% 
  summarise(spp_avg_prob = round(mean(total_prob, na.rm = T),2), #average prob zero within each COMID across the state
            spp_total_prob = round(sum(total_prob, na.rm = T), 0)) %>% #total prob zero within each COMID across the state
  left_join(spp, by = "common_name") %>% 
  mutate(prop_prob = round(spp_total_prob/prob , 2)) %>%  # proportional prob zero across the state
  select(-prob) %>% 
  pivot_longer(3:5, names_to = "variable", values_to = "value") %>% 
  filter(variable != "spp_total_prob")

spp2$common_name <- factor(spp2$common_name, levels= c("brook trout", "common shiner", "pumpkinseed"))
spp2$variable <- factor(spp2$variable, levels = c("spp_avg_prob", "prop_prob"))



sppbystate <- ggplot(data = spp2, mapping = aes(y = tolower(state), x = value, fill = common_name))+
  geom_bar(stat = "identity", position = "dodge", color = "black")+
  scale_fill_manual(values=c("royalblue3", "yellowgreen", "chocolate2"))+
  facet_wrap(~variable, scales = "free", labeller = as_labeller(c("prop_prob" = "Proportion", "spp_avg_prob" = "Average")))+
  labs(x = NULL, y = NULL, fill = "cluster")+
  theme(strip.text = element_text(size = 12, color = "black"),
        strip.background = element_rect(color = "black", fill = "grey80", linewidth = 1.5))
ggsave(sppbystate, file = "tmpfigures/paper1/sppbystate.png", 
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300)




test <- temp2 %>% 
  filter(variable == "tmp_avg_prob") %>% 
  select(-variable) %>% 
  mutate(group = "Temperature") %>% 
  rename(trait = tmp)
test2 <- tol2 %>% 
  filter(variable == "tol_avg_prob") %>% 
  select(-variable) %>% 
  mutate(group = "Tolerance") %>% 
  rename(trait = tolerance)
test3 <- spp2 %>% 
  filter(variable == "spp_avg_prob") %>% 
  select(-variable) %>% 
  mutate(group = "Species") %>% 
  rename(trait = common_name)
test4 <- clust2 %>% 
  filter(variable == "clu_avg_prob") %>% 
  select(-variable) %>% 
  mutate(group = "cluster") %>% 
  rename(trait = climclust )

test5 <- rbind(test, test2, test3, test4)

test5$trait <- factor(test5$trait, levels = c("cold", "fluvial specialist", "4", "brook trout",
                                              "warm", "generalist", "1", "pumpkinseed",
                                              "cool", "fluvial dependent",  "common shiner",
                                              "2" , "3"))

ggplot(data = test5, mapping = aes(y = trait, x = value))+
  geom_bar(stat = "identity", position = "dodge", color = "black")+
  facet_wrap(~state)+
  labs(x = "Average proportional abundance", y = NULL, fill = "trait")+
  theme(strip.text = element_text(size = 12, color = "black"),
        strip.background = element_rect(color = "black", fill = "grey80", linewidth = 1.5))




#make violin plots with the distrubiton of each trait by lat and long
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDv2_huc_state_join.RData")

#join the predictions_zero to the list of comids
NHDplusV2_NewEngCrop <- NHDplusV2_NewEngCrop %>% 
  select(COMID)
bylat <- cbind(NHDplusV2_NewEngCrop, predictions) 
bylat <- data.frame(bylat) %>% 
  select(-geometry) %>% 
  pivot_longer(2:58, values_to = "propabun", names_to = "common_name") 
bylat$common_name <- gsub("propabun_", "", pred$common_name)
bylat$common_name <- gsub(".rds", "", pred$common_name)
bylat$common_name <- gsub("\\.", " ", pred$common_name)


#join to trait data and clusters so we can filter for certain temperature groups or origin
bylat <- bylat %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(geogclust, by = "common_name") %>% 
  left_join(climclust, by = "common_name") %>% 
  left_join(final_traits, by = "common_name")
bylat <- left_join(NHDv2_huc_state_join, bylat, by = "COMID")

df1 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, tmp) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = tmp)
df2 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, tolerance) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = tolerance)
df3 <- bylat %>% 
  data.frame() %>% 
  group_by(COMID, climclust) %>% 
  summarize(propabun = sum(propabun, na.rm = T)) %>% 
  rename(trait = climclust) %>% 
  mutate(trait = as.character(trait) )
df4 <- bylat %>% 
  data.frame() %>% 
  filter(common_name == "brook trout") %>% 
  select(COMID, common_name, propabun) %>% 
  rename(trait = common_name)
df5 <- bylat %>% 
  data.frame() %>% 
  filter(common_name == "pumpkindseed") %>% 
  select(COMID, common_name, propabun) %>% 
  rename(trait = common_name)

latlong <- NHDv2_huc_state_join %>%
  data.frame() %>% 
  select(COMID, lat, long) %>% 
  unique()

df6 <- rbind(df1, df2, df3, df4, df5)
df6 <- left_join(df6, latlong, by = "COMID") %>% 
  filter(!is.na(trait)) %>% 
  mutate(latitude  = ifelse(lat > 44.51944, "high lat",
                            ifelse(lat < 42.97004, "low lat", "mid lat"))) %>% 
  mutate(longitude  = ifelse(long > -71.27307, "East", "West")) %>% 
  filter(propabun < 1.25)


df7 <- df6 %>% 
  filter(trait %in% c("1","2","3","4","5", "6"))
df8 <- df6 %>% 
  filter(trait %in% c("cold", "cool", "warm", "fluvial specialist", "fluvial dependent", "generalist", "brook trout", "pumpkinseed"))
ggplot(data = df7, mapping = aes(x = trait, y = propabun))+
  geom_boxplot()+
  facet_grid(rows = vars(longitude), cols = vars(latitude))

df8$trait <- factor(df8$trait, levels = c("cold", "cool", "warm", 
                                          "fluvial specialist", "fluvial dependent","generalist",
                                          "brook trout", "pumpkinseed"))
ggplot(data = df8, mapping = aes(x = trait, y = propabun))+
  geom_boxplot()+
  facet_grid(rows = vars(longitude), cols = vars(latitude))


  ungroup() %>% 
  group_by(COMID, tolerance) %>% 
  mutate(tol_sum = sum(propabun, na.rm = T)) %>% 
  select(COMID, lat, long, tmp, tolerance, tol_sum, tmp_sum) %>% 
  unique()


#calcuate correlations between each metric and the richness vs proportional abundance variation

r2 <- summary(lm(data = compare, coldnat_propabund ~ coldnat_rich)) #this is the better fit
#summary(lm(data = compare, coldnat_propabund ~ I(coldnat_rich^2)))
#r2  <- cor.test(compare$coldnat_propabund, compare$coldnat_rich, use = "complete.obs")
a <- ggplot(data = compare, mapping = aes(coldnat_propabund, y = coldnat_rich))+
  geom_jitter(alpha = 0.3)+
  stat_smooth(method = "lm")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10))+
  labs(x = "Proportional Abundance", y = "Species Richness")+
  geom_text(label = "Cold Native",x=.2,y=7, color = "red", size = 3)+
  geom_text(label = paste("R = ", round(r2$adj.r.squared,3), sep = ""),x=.5,y=1.5, color = "red", size = 3)+
  geom_text(label = paste("p = ", round(r2$coefficients[2,4],3), sep = ""),x=.5,y=.8, color = "red", size = 3)


#summary(lm(data = compare, coolnat_propabund ~ coolnat_rich))
r2 <- summary(lm(data = compare[compare$coolnat_propabund<0.4,], coolnat_propabund ~ I(coolnat_rich^2)))#this is the better fit
#r2  <- cor.test(compare[compare$coolnat_propabund<0.4,]$coolnat_propabund, compare[compare$coolnat_propabund<0.4,]$coolnat_rich, use = "complete.obs")
b <- ggplot(data = compare[compare$coolnat_propabund<0.4,], mapping = aes(coolnat_propabund, y = coolnat_rich))+
  geom_jitter(alpha = 0.3)+
  stat_smooth(method = "lm", formula = y~ I(x^2))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10))+
  labs(x = NULL, y = NULL)+
  geom_text(label = "Cool Native",x=.15,y=10, color = "red", size = 3)+
  geom_text(label = paste("R = ", round(r2$adj.r.squared,3), sep = ""),x=.3,y=3, color = "red", size = 3)+
  geom_text(label = paste("p = ", round(r2$coefficients[2,4],3), sep = ""),x=.3,y=2, color = "red", size = 3)


#summary(lm(data = compare, warmnat_propabund ~ warmnat_rich))
r2 <- summary(lm(data = compare[compare$warmnat_propabund<0.5,], warmnat_propabund ~ I(warmnat_rich^2)))#this is the better fit
#r2  <- cor.test(compare[compare$warmnat_propabund<0.5,]$warmnat_propabund, compare[compare$warmnat_propabund<0.5,]$warmnat_rich, use = "complete.obs")
c <- ggplot(data = compare[compare$warmnat_propabund<0.5,], mapping = aes(warmnat_propabund, y = warmnat_rich))+
  geom_jitter(alpha = 0.3)+
  stat_smooth(method = "lm", formula = y~ I(x^2))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10))+
  labs(x = NULL, y = NULL)+
  geom_text(label = "Warm Native",x=.16,y=12, color = "red", size = 3)+
  geom_text(label = paste("R = ", round(r2$adj.r.squared,3), sep = ""),x=.35,y=3, color = "red", size = 3)+
  geom_text(label = paste("p = ", round(r2$coefficients[2,4],3), sep = ""),x=.35,y=2, color = "red", size = 3)

#summary(lm(data = compare, warmnonnat_propabund ~ warmnonnat_rich))
r2 <- summary(lm(data = compare, warmnonnat_propabund ~ I(warmnonnat_rich^2)))#this is the better fit
#r2  <- cor.test(compare$warmnonnat_propabund, compare$warmnonnat_rich, use = "complete.obs")
d <- ggplot(data = compare, mapping = aes(warmnonnat_propabund, y = warmnonnat_rich))+
  geom_jitter(alpha = 0.3)+
  stat_smooth(method = "lm", formula = y~ I(x^2))+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10))+
  labs(x = NULL, y = "Species Richness")+
  geom_text(label = "Warm Non-native",x=.35,y=13.5, color = "red", size = 3)+
  geom_text(label = paste("R = ", round(r2$adj.r.squared,3), sep = ""),x=.5,y=2, color = "red", size = 3)+
  geom_text(label = paste("p = ", round(r2$coefficients[2,4],3), sep = ""),x=.5,y=1, color = "red", size = 3)


r2 <- summary(lm(data = compare, brktrt_propabun ~ brktrt_prob))#this is the better fit
#summary(lm(data = compare, brktrt_propabun ~ I(brktrt_prob^2)))
#r2  <- cor.test(compare$brktrt_propabun, compare$brktrt_prob, use = "complete.obs")
e <- ggplot(data = compare, mapping = aes(brktrt_propabun, y = brktrt_prob))+
  geom_jitter(alpha = 0.3)+
  stat_smooth(method = "lm")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10))+
  labs(x = NULL, y = "Probability of Occurrence")+
  geom_text(label = "Brook Trout",x=.2,y=1.1, color = "red", size = 3)+
  geom_text(label = paste("R = ", round(r2$adj.r.squared,3), sep = ""),x=.5,y=.3, color = "red", size = 3)+
  geom_text(label = paste("p = ", round(r2$coefficients[2,4],3), sep = ""),x=.5,y=.2, color = "red", size = 3)


c <- arrangeGrob(a, b, 
                 c, d, 
                 e, 
             ncol=3, nrow =2)
ggsave(c, file = "tmpfigures/testing234.png", 
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300)


#plot a correlation between each variable and each of the variables in the model


coldnat <- coldnat %>% 
  data.frame() %>% 
  select(-geometry) %>% 
  unique()
coolnat <- coolnat %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
warmnat <- warmnat %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
warmnonnat <- warmnonnat %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
brktrt <- brktrt %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
coldnat_1 <- coldnat_1 %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
coolnat_1 <- coolnat_1 %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
warmnat_1 <- warmnat_1 %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
warmnonnat_1 <- warmnonnat_1 %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()
brktrt_1 <- brktrt_1 %>% 
  data.frame() %>% 
  select(-geometry)%>% 
  unique()

trends <- left_join(coldnat, coolnat, by = c("tnmid", "name"))
trends <- trends %>% 
  left_join(warmnat, by = c("name", "tnmid")) %>% 
  left_join(warmnonnat, by = c("name", "tnmid")) %>% 
  left_join(brktrt, by = c("name", "tnmid")) %>% 
  left_join(coldnat_1, by = c("name", "tnmid")) %>% 
  left_join(coolnat_1, by = c("name", "tnmid")) %>% 
  left_join(warmnat_1, by = c("name", "tnmid")) %>% 
  left_join(warmnonnat_1, by = c("name", "tnmid")) %>% 
  left_join(brktrt_1, by = c("name", "tnmid"))

huc12cov <- NHDplusV2_NewEngCrop %>%
  data.frame() %>%
  select(huc12_name, huc12_tnmid, annual_mean_summer_temp, BFI_HIST, LO7Q1DT_HIST, W95_HIST,
         BFIWs, WtDepWs, PctOw_Ws, PctImp_Ws, pctAg_Ws, pctWetland_Cat, logMJJA_HIST,
         logRdCrsCat, logPctOw_Cat, huc12_damden_sqkm, huc8_damcount, lat, long, ElevCat,logWsAreaSqKm) %>% 
  unique() %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise_all(mean, na.rm = T) 

trends <- left_join(trends, huc12cov, by = c("name"= "huc12_name", "tnmid" = "huc12_tnmid"))%>% 
  filter(!is.na(lat))


df1 <- trends[, 3:12]
df2 <- trends[,13:31]

test <- data.frame(cor(df1, df2, use = "complete.obs"))
test$metric <- rownames(test)
rownames(test) <- NULL
test <- test %>% 
  select(-c(lat, long, ElevCat,logWsAreaSqKm)) %>% 
  pivot_longer(1:15, names_to = "variable", values_to = "r")

test$metric[test$metric == "coldnatrich"] <- "cold_native_rich"
test$metric[test$metric == "coolnatrich"] <- "cool_native_rich"
test$metric[test$metric == "warmnatrich"] <- "warm_native_rich"
test$metric[test$metric == "warmnonnatrich"] <- "warm_introd_rich"
test$metric[test$metric == "brktrtprob"] <- "Brook_Trout_prob"

test$metric[test$metric == "coldnatpropabund"] <- "cold_native_pa"
test$metric[test$metric == "coolnatpropabund"] <- "cool_native_pa"
test$metric[test$metric == "warmnatpropabund"] <- "warm_native_pa"
test$metric[test$metric == "warmnonnatpropabund"] <- "warm_introd_pa"
test$metric[test$metric == "brktrt_propabun"] <- "Brook_Trout_pa"

ggplot(test, aes(x = metric, y = variable, fill = r))+
  geom_tile()+
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 14))+
  scale_fill_gradient2(low = "red",
                       mid = "white",
                       high = "blue",
                       midpoint = 0)+
  labs(x = NULL, y = NULL)


```




Predict presence absence of each fish in baseline years

```{r}

load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")

#need to scal the variavles
test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)

test <- test[,c(7:8, 10:39)]

#we need to scale these variables, but first I will calucate the mean and sd of each column, bc we will need to use these values to scale these variables in the predicted scenarios

means <- sapply(test, mean, na.rm = T)
save(means, file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fishcovariates_scaling_mean.RData")
sd <- sapply(test, sd, na.rm = T)
save(sd, file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fishcovariates_scaling_sd.RData")

#scale data
test <- data.frame(scale(test))

NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1:6, 9)], test)





file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
names(predictions)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions <- cbind(predictions, tmp)
  
  
}


#join the predictions to the list of comids
NHDplusV2_NewEngCrop_baseline <- cbind(NHDplusV2_NewEngCrop, predictions)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_baseline)+
  geom_sf(aes(color = pres_creek.chub.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC12s that have an average P(occurrece)>0.05 for the baseline conditions
head(NHDplusV2_NewEngCrop_baseline)
tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count = n(),
            avg_prob = mean(mean_prob))

#watershed shape files
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")
huc12 <- huc12 %>% 
  select(name, tnmid)
#align prediction results with the unscaled covariates and make plots
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")
pred <- cbind(NHDplusV2_NewEngCrop, predictions)
pred <- pred %>%
  data.frame %>% 
  pivot_longer(40:96, values_to = "prob", names_to = "common_name") %>% 
  mutate(occurrence = ifelse(prob>0.3, 1, 0))
pred$common_name <- gsub("pres_", "", pred$common_name)
pred$common_name <- gsub(".rds", "", pred$common_name)
pred$common_name <- gsub("\\.", " ", pred$common_name)
#join to trait data so we can filter for certain temperature groups or origin
#fish traits
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_traits.RData")
temperature <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 1,
                  range = cell_cols("A:G")) %>% 
  pivot_longer(2:7, names_to = "state", values_to = "tmp") %>% 
  filter(!is.na(tmp),
         !tmp == "eury",
         !(common_name %in% c("american brook lamprey") & tmp == "cold"),
         !(common_name %in% c("common shiner", "white sucker", "smallmouth bass", "fallfish") & tmp == "warm")) %>% 
  select(-state) %>% 
  unique()

origin <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 2,
                  range = cell_cols("A:G"))%>% 
  pivot_longer(2:7, names_to = "state", values_to = "origin") %>% 
  filter(!is.na(origin),
         !(common_name == "spottail shiner" & origin == "introduced"),
         !origin == "unk") %>% 
  select(-state) %>%  
  unique()

pred <- pred %>% 
  left_join(temperature, by = "common_name") %>% 
  left_join(origin, by = "common_name")

#plot cold water native species richness
coldnat <- pred %>% 
  select(huc12_name, huc12_tnmid, common_name, tmp, origin, occurrence) %>% 
  unique() %>% 
  filter(tmp == "cold" & origin == "native" & occurrence == 1) %>%
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(coldnatrichness = n())
coldnat <- left_join(huc12, coldnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = coldnat)+
  geom_sf(aes(fill = coldnatrichness, color = coldnatrichness))

#plot cool water native species richness
coolnat <- pred %>% 
  select(huc12_name, huc12_tnmid, common_name, tmp, origin, occurrence) %>% 
  unique() %>% 
  filter(tmp == "cool" & origin == "native" & occurrence == 1) %>%
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(coolnatrichness = n())
coolnat <- left_join(huc12, coolnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = coolnat)+
  geom_sf(aes(fill = coolnatrichness, color = coolnatrichness))

#plot warm water native species richness
warmnat <- pred %>% 
  select(huc12_name, huc12_tnmid, common_name, tmp, origin, occurrence) %>% 
  unique() %>% 
  filter(tmp == "warm" & origin == "native" & occurrence == 1) %>%
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(warmnatrichness = n())
warmnat <- left_join(huc12, warmnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = warmnat)+
  geom_sf(aes(fill = warmnatrichness, color = warmnatrichness))

#plot warm water nonnative species richness
warmnonnat <- pred %>% 
  select(huc12_name, huc12_tnmid, common_name, tmp, origin, occurrence) %>% 
  unique() %>% 
  filter(tmp == "warm" & origin == "introduced" & occurrence == 1) %>%
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(warmnonnatrichness = n())
warmnonnat <- left_join(huc12, warmnonnat, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = warmnonnat)+
  geom_sf(aes(fill = warmnonnatrichness, color = warmnonnatrichness))

#plot native species beta richness
nathuc12 <- pred %>% 
  select(huc8_name, huc8_tnmid, huc12_name, huc12_tnmid, common_name, origin, occurrence) %>% 
  unique() %>% 
  filter(origin == "native" & occurrence == 1) %>%
  group_by(huc8_name, huc8_tnmid, huc12_name, huc12_tnmid) %>% 
  summarise(nathuc12_alpharichness = n())

nathuc8 <- pred %>% 
  select(huc8_name, huc8_tnmid, common_name, origin, occurrence) %>% 
  unique() %>% 
  filter(origin == "native" & occurrence == 1) %>%
  group_by(huc8_name, huc8_tnmid) %>% 
  summarise(nathuc8_gammarichness = n())
beta <- left_join(nathuc12, nathuc8, by = c("huc8_name", "huc8_tnmid")) %>% 
  mutate(beta_richness = nathuc12_alpharichness / nathuc8_gammarichness)

beta <- left_join(huc12, beta, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = beta)+
  geom_sf(aes(fill = beta_richness, color = beta_richness))

#plot probability of brook trout occurrence
brktrt <- pred %>% 
  select(huc12_name, huc12_tnmid, common_name, prob) %>% 
  unique() %>% 
  filter(common_name == "brook trout") %>%
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise(brktrt_prob = mean(prob, na.rm = T))
brktrt <- left_join(huc12, brktrt, by = c("name" = "huc12_name", "tnmid" = "huc12_tnmid"))
ggplot(data = brktrt)+
  geom_sf(aes(fill = brktrt_prob, color = brktrt_prob))


coldnat <- coldnat %>% 
  data.frame() %>% 
  select(-geometry)
coolnat <- coolnat %>% 
  data.frame() %>% 
  select(-geometry)
warmnat <- warmnat %>% 
  data.frame() %>% 
  select(-geometry)
warmnonnat <- warmnonnat %>% 
  data.frame() %>% 
  select(-geometry)
beta <- beta %>% 
  data.frame() %>% 
  select(-geometry)
brktrt <- brktrt %>% 
  data.frame() %>% 
  select(-geometry)

trends <- left_join(coldnat, coolnat, by = c("name", "tnmid"))
trends <- trends %>% 
  left_join(warmnat, by = c("name", "tnmid")) %>% 
  left_join(warmnonnat, by = c("name", "tnmid")) %>% 
  left_join(beta, by = c("name", "tnmid")) %>% 
  left_join(brktrt, by = c("name", "tnmid"))
              

huc12cov <- NHDplusV2_NewEngCrop %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, 7, 8, 10:39) %>% 
  group_by(huc12_name, huc12_tnmid) %>% 
  summarise_all(mean, na.rm = T)

trends <- left_join(trends, huc12cov, by = c("name"= "huc12_name", "tnmid" = "huc12_tnmid"))




#climate change

#load the 2080 file that has the projected stream temperature and streamflow covariate values
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates_2080.RData")


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)

#this is what I did for NAB but now we're using the actual climate change scnearios prepared above
#NHDplusV2_NewEngCrop_cc <- NHDplusV2_NewEngCrop %>% 
#  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2
#         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_cc <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc, type = "response"))
names(predictions_cc)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_cc <- cbind(predictions_cc, tmp)
  
  
}


#join the predictions_cc to the list of comids
NHDplusV2_NewEngCrop_cc <- cbind(NHDplusV2_NewEngCrop_cc, predictions_cc)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_cc)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC12s that have an average P(occurrece)>0.05 for the climate change conditions
head(NHDplusV2_NewEngCrop_cc)
tmp_cc <- NHDplusV2_NewEngCrop_cc %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_cc = n(),
            avg_prob_cc = mean(mean_prob))




#climate change and connectivity reduction


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(huc8_damcount = huc8_damcount * 1.5,
         huc12_damden_sqkm = huc12_damden_sqkm * 1.5,
         logRdCrsCat = logRdCrsCat * 1.5) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_dvlp_cnnctv <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#this is a scenario we used for NAB the devleopment scenario
# NHDplusV2_NewEngCrop_ccdvlp <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
#          PctImp_Ws = PctImp_Ws+2,
#          pctAg_Ws = pctAg_Ws+2,
#          logRdCrsCat = logRdCrsCat+2,
#          huc12_damden_sqkm = huc12_damden_sqkm+2,
#          huc8_damcount = huc8_damcount+2
#          )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccdvlp_cnnctv <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cnnctv, type = "response"))
names(predictions_ccdvlp_cnnctv)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cnnctv, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccdvlp_cnnctv <- cbind(predictions_ccdvlp_cnnctv, tmp)
  
  
}


#join the predictions_ccdvlp_cnnctv to the list of comids
NHDplusV2_NewEngCrop_cc_dvlp_cnnctv <- cbind(NHDplusV2_NewEngCrop_cc_dvlp_cnnctv, predictions_ccdvlp_cnnctv)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_cc_dvlp_cnnctv)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the climate change and connectivity reduction conditions
head(NHDplusV2_NewEngCrop_cc_dvlp_cnnctv)
tmp_ccdvlp_cnnctv <- NHDplusV2_NewEngCrop_cc_dvlp_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccdvlp_cnnctv = n(),
            avg_prob_ccdvlp_cnnctv = mean(mean_prob))



#climate change and connectivity improvements


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(huc8_damcount = huc8_damcount * .75,
         huc12_damden_sqkm = huc12_damden_sqkm * .75,
         logRdCrsCat = logRdCrsCat * .75) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_mgmt_cnnctv <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccmgmt_cnnctv <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cnnctv, type = "response"))
names(predictions_ccmgmt_cnnctv)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cnnctv, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccmgmt_cnnctv <- cbind(predictions_ccmgmt_cnnctv, tmp)
  
  
}


#join the predictions_ccmgmt_cnnctv to the list of comids
NHDplusV2_NewEngCrop_cc_mgmt_cnnctv <- cbind(NHDplusV2_NewEngCrop_cc_mgmt_cnnctv, predictions_ccmgmt_cnnctv)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_cc_mgmt_cnnctv)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the climate change and connectivity improvement conditions
head(NHDplusV2_NewEngCrop_cc_mgmt_cnnctv)
tmp_ccmgmt_cnnctv <- NHDplusV2_NewEngCrop_cc_mgmt_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccmgmt_cnnctv = n(),
            avg_prob_ccmgmt_cnnctv = mean(mean_prob))







#climate change and land cover developments (ie increase in ag and impervious)


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(PctImp_Ws = PctImp_Ws * 1.5,
         pctAg_Ws = pctAg_Ws * 1.5) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_dvlp_cvr <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccdvlp_cvr <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cvr, type = "response"))
names(predictions_ccdvlp_cvr)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cvr, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccdvlp_cvr <- cbind(predictions_ccdvlp_cvr, tmp)
  
  
}


#join the predictions_ccdvlp_cvr to the list of comids
NHDplusV2_NewEngCrop_cc_dvlp_cvr <- cbind(NHDplusV2_NewEngCrop_cc_dvlp_cvr, predictions_ccdvlp_cvr)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_cc_dvlp_cvr)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the climate change and increased ag and impervious
head(NHDplusV2_NewEngCrop_cc_dvlp_cvr)
tmp_ccdvlp_cvr <- NHDplusV2_NewEngCrop_cc_dvlp_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccdvlp_cvr = n(),
            avg_prob_ccdvlp_cvr = mean(mean_prob))




#climate change and land cover improvements (ie reduced  ag and impervious)


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(PctImp_Ws = PctImp_Ws * .75,
         pctAg_Ws = pctAg_Ws * .75) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_mgmt_cvr <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccmgmt_cvr <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cvr, type = "response"))
names(predictions_ccmgmt_cvr)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cvr, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccmgmt_cvr <- cbind(predictions_ccmgmt_cvr, tmp)
  
  
}


#join the predictions_ccmgmt_cvr to the list of comids
NHDplusV2_NewEngCrop_cc_mgmt_cvr <- cbind(NHDplusV2_NewEngCrop_cc_mgmt_cvr, predictions_ccmgmt_cvr)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_cc_mgmt_cvr)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the climate change and reduced ag and impervious
head(NHDplusV2_NewEngCrop_cc_mgmt_cvr)
tmp_ccmgmt_cvr <- NHDplusV2_NewEngCrop_cc_mgmt_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccmgmt_cvr = n(),
            avg_prob_ccmgmt_cvr = mean(mean_prob))









#climate change and Development

NHDplusV2_NewEngCrop_ccdvlp <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
         PctImp_Ws = PctImp_Ws+2,
         pctAg_Ws = pctAg_Ws+2,
         logRdCrsCat = logRdCrsCat+2,
         huc12_damden_sqkm = huc12_damden_sqkm+2,
         huc8_damcount = huc8_damcount+2
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccdvlp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_ccdvlp, type = "response"))
names(predictions_ccdvlp)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_ccdvlp, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccdvlp <- cbind(predictions_ccdvlp, tmp)
  
  
}


#join the predictions_ccdvlp to the list of comids
NHDplusV2_NewEngCrop_ccdvlp <- cbind(NHDplusV2_NewEngCrop_ccdvlp, predictions_ccdvlp)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_ccdvlp)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the mgmt conditions
head(NHDplusV2_NewEngCrop_ccdvlp)
tmp_ccdvlp <- NHDplusV2_NewEngCrop_ccdvlp %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccdvlp = n(),
            avg_prob_ccdvlp = mean(mean_prob))







#climate change and management

NHDplusV2_NewEngCrop_ccmgmt <- NHDplusV2_NewEngCrop %>% 
  mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
         PctImp_Ws = PctImp_Ws-2,
         pctAg_Ws = pctAg_Ws-2,
         logRdCrsCat = logRdCrsCat-2,
         huc12_damden_sqkm = huc12_damden_sqkm-2,
         huc8_damcount = huc8_damcount-2
         )



file.list <- list.files("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects", pattern = "pres_")

i <- 1

mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
predictions_ccmgmt <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_ccmgmt, type = "response"))
names(predictions_ccmgmt)[1] <- file.list[i]




for (i in 2:57) { 
  
  
   mdl <- readRDS(paste("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/", file.list[i], sep = ""))
  
  tmp <- data.frame("test" = predict(mdl, newdata = NHDplusV2_NewEngCrop_ccmgmt, type = "response"))
  names(tmp)[1] <- file.list[i]
  
  predictions_ccmgmt <- cbind(predictions_ccmgmt, tmp)
  
  
}


#join the predictions_ccmgmt to the list of comids
NHDplusV2_NewEngCrop_ccmgmt <- cbind(NHDplusV2_NewEngCrop_ccmgmt, predictions_ccmgmt)

#sample plot
ggplot(data = NHDplusV2_NewEngCrop_ccmgmt)+
  geom_sf(aes(color = pres_brook.trout.rds))+
  scale_color_gradient2(low = "blue",
                        mid = "yellow",
                        high = "red",
                        midpoint = 0.5)



#this calcuated the total number of HUC8s that have an average P(occurrece)>0.05 for the mgmt conditions
head(NHDplusV2_NewEngCrop_ccmgmt)
tmp_ccmgmt <- NHDplusV2_NewEngCrop_ccmgmt %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") %>% 
  group_by(huc12_tnmid, huc12_name, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(common_name) %>% 
  summarise(count_ccmgmt = n(),
            avg_prob_ccmgmt = mean(mean_prob))










compare <- full_join(tmp_baseline, tmp_cc, by  = "common_name")

compare <- full_join(compare, tmp_ccdvlp, by  = "common_name")

compare <- full_join(compare, tmp_ccmgmt, by  = "common_name")


names(compare)

compare <- compare %>% 
  mutate(base_ccmgmt = round(((count_ccmgmt - count)/count*100),0),
         base_ccdvlp = round(((count_ccdvlp - count )/count*100),0),
         base_cc = round(((count_cc - count)/count*100),0),
         basep_ccmgmtp = round(((avg_prob_ccmgmt - avg_prob)/avg_prob*100),0),
         basep_ccdvlpp = round(((avg_prob_ccdvlp - avg_prob)/avg_prob*100),0),
         basep_ccp = round(((avg_prob_cc - avg_prob)/avg_prob*100),0))

compare$common_name <- gsub(".rds", "", compare$common_name)

compare$common_name <- gsub("pres_", "", compare$common_name)

compare$common_name <- gsub("\\.", " ", compare$common_name)

#remove spp that didnt have model convergence
compare <- compare %>% 
  filter(! common_name %in% c("bowfin", "white catfish", "rosyside dace", 
                              "mimic shiner", "walleye", "round whitefish", 
                              "roseface shiner",  "spotfin shiner"))

load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_occurrence.RData")
names <- fish_occurrence %>% 
  select(common_name, scientific_name) %>% 
  unique()

compare <- left_join(compare, names, by = "common_name") %>% 
  select(scientific_name, 1:15) %>% 
  arrange(desc(count))

write.csv(compare, file = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/presabs_predictions.csv")



#calcuate spp richness by huc12 for each basin

#fish traits
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/fish_traits.RData")
temperature <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 1,
                  range = cell_cols("A:H")) %>% 
  select(common_name, all) %>% 
  rename(tmp = all)
origin <- read_xlsx("C:/Users/jenrogers/Documents/necascFreshwaterBio/spp_data/thermalpref_origin_tolerance.xlsx",
                  sheet = 2,
                  range = cell_cols("A:G"))%>% 
  pivot_longer(2:7, names_to = "state", values_to = "origin") %>% 
  filter(state == "MA") %>% 
  select(common_name, origin)
#Even though the origin vary by state, for now, were just going to use the MA designations


#### species richness by origin for the climate change, baseline, dvlp conn, dvlp cvr, mgmt conn, and mgmt cvr


tmp_cc <- NHDplusV2_NewEngCrop_cc %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_cc$common_name <- gsub(".rds", "", tmp_cc$common_name)
tmp_cc$common_name <- gsub("pres_", "", tmp_cc$common_name)
tmp_cc$common_name <- gsub("\\.", " ", tmp_cc$common_name)

tmp_cc <- tmp_cc %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_cc = n()) %>% 
  pivot_wider(names_from = origin, values_from = rich_cc) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_cc = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



tmp_ccdvlp_cnnctv <- NHDplusV2_NewEngCrop_cc_dvlp_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccdvlp_cnnctv$common_name <- gsub(".rds", "", tmp_ccdvlp_cnnctv$common_name)
tmp_ccdvlp_cnnctv$common_name <- gsub("pres_", "", tmp_ccdvlp_cnnctv$common_name)
tmp_ccdvlp_cnnctv$common_name <- gsub("\\.", " ", tmp_ccdvlp_cnnctv$common_name)

tmp_ccdvlp_cnnctv <-  tmp_ccdvlp_cnnctv %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_ccdvlp_cnnctv = n())%>% 
  pivot_wider(names_from = origin, values_from = rich_ccdvlp_cnnctv) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_ccdvlp_cnnctv = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



tmp_ccdvlp_cvr <- NHDplusV2_NewEngCrop_cc_dvlp_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccdvlp_cvr$common_name <- gsub(".rds", "", tmp_ccdvlp_cvr$common_name)
tmp_ccdvlp_cvr$common_name <- gsub("pres_", "", tmp_ccdvlp_cvr$common_name)
tmp_ccdvlp_cvr$common_name <- gsub("\\.", " ", tmp_ccdvlp_cvr$common_name)

tmp_ccdvlp_cvr <-  tmp_ccdvlp_cvr %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_ccdvlp_cvr = n())%>% 
  pivot_wider(names_from = origin, values_from = rich_ccdvlp_cvr) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_ccdvlp_cvr = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)


tmp_ccmgmt_cnnctv <- NHDplusV2_NewEngCrop_cc_mgmt_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccmgmt_cnnctv$common_name <- gsub(".rds", "", tmp_ccmgmt_cnnctv$common_name)
tmp_ccmgmt_cnnctv$common_name <- gsub("pres_", "", tmp_ccmgmt_cnnctv$common_name)
tmp_ccmgmt_cnnctv$common_name <- gsub("\\.", " ", tmp_ccmgmt_cnnctv$common_name)

tmp_ccmgmt_cnnctv <- tmp_ccmgmt_cnnctv %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_ccmgmt_cnnctv = n()) %>% 
  pivot_wider(names_from = origin, values_from = rich_ccmgmt_cnnctv) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_ccmgmt_cnnctv = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)


tmp_ccmgmt_cvr <- NHDplusV2_NewEngCrop_cc_mgmt_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccmgmt_cvr$common_name <- gsub(".rds", "", tmp_ccmgmt_cvr$common_name)
tmp_ccmgmt_cvr$common_name <- gsub("pres_", "", tmp_ccmgmt_cvr$common_name)
tmp_ccmgmt_cvr$common_name <- gsub("\\.", " ", tmp_ccmgmt_cvr$common_name)

tmp_ccmgmt_cvr <- tmp_ccmgmt_cvr %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_ccmgmt_cvr = n()) %>% 
  pivot_wider(names_from = origin, values_from = rich_ccmgmt_cvr) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_ccmgmt_cvr = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_baseline$common_name <- gsub(".rds", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("pres_", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("\\.", " ", tmp_baseline$common_name)

tmp_baseline <- tmp_baseline %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, origin, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, origin) %>% 
  summarise(rich_baseline = n())%>% 
  pivot_wider(names_from = origin, values_from = rich_baseline) %>% 
  mutate(sum = sum(native, introduced, na.rm = T),
         prop_native_baseline = native/sum) %>% 
  select(-introduced, -native, -'NA', -sum)



huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")

states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")


# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


# huc8 <- left_join(huc8, tmp_baseline, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_cc, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccdvlp, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccmgmt, by = "huc8_name")

huc12 <- left_join(huc12, tmp_baseline, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_cc, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccdvlp_cnnctv, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccdvlp_cvr, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccmgmt_cnnctv, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccmgmt_cvr, by = c("huc12_tnmid", "huc12_name"))

#calcuate change in climate change from baseline, but change in the other two from climate change
huc12 <- huc12 %>% 
  mutate(change_ccdvlp_cnnctv = prop_native_ccdvlp_cnnctv - prop_native_baseline,
         change_ccdvlp_crv = prop_native_ccdvlp_cvr - prop_native_baseline,
         change_ccmgmt_cnnctv = prop_native_ccmgmt_cnnctv - prop_native_baseline,
         change_ccmgmt_crv = prop_native_ccmgmt_cvr - prop_native_baseline,
         change_cc = prop_native_cc - prop_native_baseline)

#plot absolute values of proportaional richness of native spp
huc12a <- huc12 %>% 
  select(3:9) %>% 
  pivot_longer(2:7, names_to = "scenario", values_to = "prop_richness") %>% 
  filter(!is.na(prop_richness))
huc12a$scenario[huc12a$scenario == "prop_native_baseline"] <- "baseline"
huc12a$scenario[huc12a$scenario == "prop_native_cc"] <- "cc"
huc12a$scenario[huc12a$scenario == "prop_native_ccdvlp_cnnctv"] <- "cc + dvlp + cnn"
huc12a$scenario[huc12a$scenario == "prop_native_ccdvlp_cvr"] <- "cc + dvlp + cvr"
huc12a$scenario[huc12a$scenario == "prop_native_ccmgmt_cnnctv"] <- "cc + mgmt + cnn"
huc12a$scenario[huc12a$scenario == "prop_native_ccmgmt_cvr"] <- "cc + mgmt + cvr"


ggplot(data = huc12a)+
  geom_sf(aes(fill = prop_richness), color = NA)+
  scale_fill_viridis_c()+
  facet_wrap(~scenario, nrow = 2)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Native Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_native_spp_richness.png",
    plot = last_plot(),
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300
  )



#plot change of proportaional richness of native spp
huc12b <- huc12 %>% 
  select(3, 11:15) %>% 
  pivot_longer(2:6, names_to = "scenario", values_to = "change") %>% 
  filter(!is.na(change))
huc12b$scenario[huc12b$scenario == "prop_native_baseline"] <- "baseline"
huc12b$scenario[huc12b$scenario == "prop_native_cc"] <- "cc"
huc12b$scenario[huc12b$scenario == "prop_native_ccdvlp_cnnctv"] <- "cc + dvlp + cnn"
huc12b$scenario[huc12b$scenario == "prop_native_ccdvlp_cvr"] <- "cc + dvlp + cvr"
huc12b$scenario[huc12b$scenario == "prop_native_ccmgmt_cnnctv"] <- "cc + mgmt + cnn"
huc12b$scenario[huc12b$scenario == "prop_native_ccmgmt_cvr"] <- "cc + mgmt + cvr"


ggplot(data = huc12b)+
  geom_sf(aes(fill = change), color = NA)+
  scale_fill_gradient2(low = "blue",
                        mid = "white",
                        high = "red",
                        midpoint = 0)+
  facet_wrap(~scenario, nrow = 2)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Change Prop Native Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_native_spp_richness_change.png",
    plot = last_plot(),
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300
  )





#### species richness by temperature


tmp_cc <- NHDplusV2_NewEngCrop_cc %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_cc$common_name <- gsub(".rds", "", tmp_cc$common_name)
tmp_cc$common_name <- gsub("pres_", "", tmp_cc$common_name)
tmp_cc$common_name <- gsub("\\.", " ", tmp_cc$common_name)

tmp_cc <- tmp_cc %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name") %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_cc = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_cc) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_cc = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)



tmp_ccdvlp_cnnctv <- NHDplusV2_NewEngCrop_cc_dvlp_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccdvlp_cnnctv$common_name <- gsub(".rds", "", tmp_ccdvlp_cnnctv$common_name)
tmp_ccdvlp_cnnctv$common_name <- gsub("pres_", "", tmp_ccdvlp_cnnctv$common_name)
tmp_ccdvlp_cnnctv$common_name <- gsub("\\.", " ", tmp_ccdvlp_cnnctv$common_name)

tmp_ccdvlp_cnnctv <-  tmp_ccdvlp_cnnctv %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_ccdvlp_cnnctv = n())%>% 
  pivot_wider(names_from = tmp, values_from = rich_ccdvlp_cnnctv) %>% 
  mutate(sum = sum(warm, cold, cool, na.rm = T),
         prop_cold_ccdvlp_cnnctv = cold/sum) %>% 
  select(-warm, -cold, -cool, -sum, -eury)


tmp_ccdvlp_cvr <- NHDplusV2_NewEngCrop_cc_dvlp_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccdvlp_cvr$common_name <- gsub(".rds", "", tmp_ccdvlp_cvr$common_name)
tmp_ccdvlp_cvr$common_name <- gsub("pres_", "", tmp_ccdvlp_cvr$common_name)
tmp_ccdvlp_cvr$common_name <- gsub("\\.", " ", tmp_ccdvlp_cvr$common_name)

tmp_ccdvlp_cvr <-  tmp_ccdvlp_cvr %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_ccdvlp_cvr = n())%>% 
  pivot_wider(names_from = tmp, values_from = rich_ccdvlp_cvr) %>% 
  mutate(sum = sum(warm, cold, cool, na.rm = T),
         prop_cold_ccdvlp_cvr = cold/sum) %>% 
  select(-warm, -cold, -cool, -sum, -eury)



tmp_ccmgmt_cnnctv <- NHDplusV2_NewEngCrop_cc_mgmt_cnnctv %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccmgmt_cnnctv$common_name <- gsub(".rds", "", tmp_ccmgmt_cnnctv$common_name)
tmp_ccmgmt_cnnctv$common_name <- gsub("pres_", "", tmp_ccmgmt_cnnctv$common_name)
tmp_ccmgmt_cnnctv$common_name <- gsub("\\.", " ", tmp_ccmgmt_cnnctv$common_name)

tmp_ccmgmt_cnnctv <- tmp_ccmgmt_cnnctv %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_ccmgmt_cnnctv = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_ccmgmt_cnnctv) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_mgmt_cnnctv = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)


tmp_ccmgmt_cvr <- NHDplusV2_NewEngCrop_cc_mgmt_cvr %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_ccmgmt_cvr$common_name <- gsub(".rds", "", tmp_ccmgmt_cvr$common_name)
tmp_ccmgmt_cvr$common_name <- gsub("pres_", "", tmp_ccmgmt_cvr$common_name)
tmp_ccmgmt_cvr$common_name <- gsub("\\.", " ", tmp_ccmgmt_cvr$common_name)

tmp_ccmgmt_cvr <- tmp_ccmgmt_cvr %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_ccmgmt_cvr = n()) %>% 
  pivot_wider(names_from = tmp, values_from = rich_ccmgmt_cvr) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_mgmt_cvr = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)




tmp_baseline <- NHDplusV2_NewEngCrop_baseline %>% 
  data.frame() %>% 
  select(huc12_tnmid, huc12_name, 40:96) %>% 
  pivot_longer(3:59, names_to = "common_name") 
tmp_baseline$common_name <- gsub(".rds", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("pres_", "", tmp_baseline$common_name)
tmp_baseline$common_name <- gsub("\\.", " ", tmp_baseline$common_name)

tmp_baseline <- tmp_baseline %>% 
  left_join(final_traits, by = "common_name") %>% 
  left_join(origin, by = "common_name")  %>% 
  left_join(temperature, by = "common_name") %>%  
  group_by(huc12_tnmid, huc12_name, tmp, common_name) %>% 
  summarise(mean_prob = mean(value, na.rm = T)) %>% 
  filter(mean_prob >0.05) %>%
  ungroup() %>% 
  group_by(huc12_tnmid, huc12_name, tmp) %>% 
  summarise(rich_baseline = n())%>% 
  pivot_wider(names_from = tmp, values_from = rich_baseline) %>% 
  mutate(sum = sum(warm, cold, cool, eury, na.rm = T),
         prop_cold_baseline = cold/sum) %>% 
  select(-warm, -cold, -cool, -eury, -sum)



huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")

states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")


# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


# huc8 <- left_join(huc8, tmp_baseline, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_cc, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccdvlp, by = "huc8_name")
# huc8 <- left_join(huc8, tmp_ccmgmt, by = "huc8_name")

huc12 <- left_join(huc12, tmp_baseline, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_cc, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccdvlp_cnnctv, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccdvlp_cvr, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccmgmt_cnnctv, by = c("huc12_tnmid", "huc12_name"))
huc12 <- left_join(huc12, tmp_ccmgmt_cvr, by = c("huc12_tnmid", "huc12_name"))

huc12 <- huc12 %>% 
  mutate(change_cc = prop_cold_cc - prop_cold_baseline,
         change_ccdvlp_cnnctv = prop_cold_ccdvlp_cnnctv - prop_cold_baseline,
         change_ccdvlp_cvr = prop_cold_ccdvlp_cvr - prop_cold_baseline,
         change_ccmgmt_cnnctv = prop_cold_mgmt_cnnctv - prop_cold_baseline,
         change_ccmgmt_cvr = prop_cold_mgmt_cvr - prop_cold_baseline,
         )

#plot absolute values of proportion of cold spp richness
huc12a <- huc12 %>% 
  select(3:9) %>% 
  pivot_longer(2:7, names_to = "scenario", values_to = "prop_richness") %>% 
  filter(!is.na(prop_richness))
huc12a$scenario[huc12a$scenario == "prop_cold_baseline"] <- "baseline"
huc12a$scenario[huc12a$scenario == "prop_cold_cc"] <- "cc"
huc12a$scenario[huc12a$scenario == "prop_cold_ccdvlp_cnnctv"] <- "cc + dvlp + cnn"
huc12a$scenario[huc12a$scenario == "prop_cold_ccdvlp_cvr"] <- "cc + dvlp + cvr"
huc12a$scenario[huc12a$scenario == "prop_cold_mgmt_cnnctv"] <- "cc + mgmt + cnn"
huc12a$scenario[huc12a$scenario == "prop_cold_mgmt_cvr"] <- "cc + mgmt + cvr"


ggplot(data = huc12a)+
  geom_sf(aes(fill = prop_richness), color = NA)+
  scale_fill_viridis_c()+
  facet_wrap(~scenario, nrow = 2)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Cold Species Richness")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_cold_spp_richness.png",
    plot = last_plot(),
    width = 18,
    height = 12,
    units = "cm",
    dpi = 300
  )

#plot change of proportion of cold spp richness
huc12a <- huc12 %>% 
  select(3, 11:15) %>% 
  pivot_longer(2:6, names_to = "scenario", values_to = "change") %>% 
  filter(!is.na(change))
huc12a$scenario[huc12a$scenario == "prop_cold_cc"] <- "cc"
huc12a$scenario[huc12a$scenario == "prop_cold_ccdvlp_cnnctv"] <- "cc + dvlp + cnn"
huc12a$scenario[huc12a$scenario == "prop_cold_ccdvlp_cvr"] <- "cc + dvlp + cvr"
huc12a$scenario[huc12a$scenario == "prop_cold_mgmt_cnnctv"] <- "cc + mgmt + cnn"
huc12a$scenario[huc12a$scenario == "prop_cold_mgmt_cvr"] <- "cc + mgmt + cvr"


ggplot(data = huc12a)+
  geom_sf(aes(fill = change), color = NA)+
  scale_fill_gradient2(low = "blue",
                        mid = "white",
                        high = "red",
                        midpoint = 0)+
  facet_wrap(~scenario, nrow = 2)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    ggtitle(label = "Prop Cold Species Richness Change")


ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/predicted_cold_spp_richness_change.png",
    plot = last_plot(),
    width = 9,
    height = 12,
    units = "cm",
    dpi = 300
  )

```




multinomial logistic regression predictions

```{r}
library(foreign)
library(nnet)

#load prediction dataset
load(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates.RData")


#load and prep huc12

huc12 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU12/WBDHU12_NE.shp")


sf_use_s2(FALSE)

huc12 <- huc12 %>% 
  select(tnmid, areasqkm , name) %>% 
  rename(huc12_areasqkm = areasqkm, huc12_name= name, huc12_tnmid = tnmid)
huc12 <- huc12[!duplicated(huc12$huc12_tnmid),]#Remove the duplicated TNMID fields
#this df needs aditional editting
#Outlet Missisquoi River - HUc12_name this is the same shape, but it actually has two separate tnmid
#Outlet Sutton River and Riviere Sutton are the same shape, but have different HUC 12 names and have different tnmid
#Ruiss Coslett-Riviere Aux Brochets vs Groat Creek are the same shape with different names and tmnid

huc12 <- huc12 %>% 
  filter(huc12_tnmid != "{7964F492-75EA-4AA7-8E77-A96D99348771}",
         huc12_name != "Riviere Sutton",
         huc12_name != "Ruiss Coslett-Riviere Aux Brochets")

#load and prep huc8
# huc8 <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/NHDplus/WBDHU8/WBDHU8_NE.shp")
# sf_use_s2(FALSE)
# huc8 <- huc8 %>% 
#   select(tnmid, areasqkm, name) %>% 
#   rename(huc8_areasqkm = areasqkm, huc8_name= name, huc8_tnmid = tnmid)
# huc8 <- huc8[!duplicated(huc8$huc8_tnmid),]#Remove the duplicated TNMID fields


#load states
states <- st_read("C:/Users/jenrogers/Documents/necascFreshwaterBio/SpatialData/newenglandshape/NEWENGLAND_POLY.shp")

#need to scale the variables in NHDplusV2_NewEngCrop

test <- NHDplusV2_NewEngCrop %>% 
  data.frame() %>% 
  select(-geometry)
test <- test[,c(7:8, 10:39)]
test <- data.frame(scale(test))
NHDplusV2_NewEngCrop <- cbind((NHDplusV2_NewEngCrop)[,c(1, 5, 6)], test)

#load model
mdl <- readRDS(file = "C:/Users/jenrogers/Documents/necascFreshwaterBio/model_objects/trait_temp.rds")







#prediction using baseline values:

tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>% 
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_baseline <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_baseline <- temptraits_baseline %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_baseline)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_baseline.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )



ggplot(data = temptraits_baseline, aes(x = huc12_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")

ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_baseline_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )









#prediction using climate change values values:


#load the 2080 file that has the projected stream temperature and streamflow covariate values
load("C:/Users/jenrogers/Documents/necascFreshwaterBio/model_datafiles/NHDplusV2_NewEngCrop_covariates_2080.RData")


#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#this is what we used for the NAB conferencce
# NHDplusV2_NewEngCrop_cc <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2
#          )


tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>% 
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_cc <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_cc <- temptraits_cc %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_cc)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_cc, aes(x = huc12_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")

ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )










#prediction using climate change and development  - connectivity reduction:

#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(huc8_damcount = huc8_damcount * 5,
         huc12_damden_sqkm = huc12_damden_sqkm * 5,
         logRdCrsCat = logRdCrsCat * 5) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_dvlp_cnnctv <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#this is what we used for the NAB conference
# NHDplusV2_NewEngCrop_ccdvlp <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
#          PctImp_Ws = PctImp_Ws + 2,
#          pctAg_Ws = pctAg_Ws + 2,
#          logRdCrsCat = logRdCrsCat + 2,
#          huc12_damden_sqkm = huc12_damden_sqkm + 2,
#          huc8_damcount = huc8_damcount + 2
#          )


tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cnnctv, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc_dvlp_cnnctv, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccdvlp_cnn <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccdvlp_cnn <- temptraits_ccdvlp_cnn %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccdvlp_cnn)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp_cnn.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccdvlp_cnn, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp_cnn_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )







#prediction using climate change and management values: increase in connectivity

test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(huc8_damcount = huc8_damcount * .1,
         huc12_damden_sqkm = huc12_damden_sqkm * .1,
         logRdCrsCat = logRdCrsCat * .1) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_mgmt_cnnctv <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#used for NAB
# NHDplusV2_NewEngCrop_ccmgmt <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
#          PctImp_Ws = PctImp_Ws - 2,
#          pctAg_Ws = pctAg_Ws - 2,
#          logRdCrsCat = logRdCrsCat - 2,
#          huc12_damden_sqkm = huc12_damden_sqkm - 2,
#          huc8_damcount = huc8_damcount - 2,
#          
#          )

tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cnnctv, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc_mgmt_cnnctv, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccmgmt_cnn <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccmgmt_cnn <- temptraits_ccmgmt_cnn %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccmgmt_cnn)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt_cnn.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccmgmt_cnn, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt_cnn_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )






#prediction using climate change and development  - cover reduction:

#need to get the variables named the same as the baseline dataframe and need to order the variables in the same way so that we can scale them
test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(PctImp_Ws = PctImp_Ws * 5,
         pctAg_Ws = pctAg_Ws * 5) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_dvlp_cvr <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#this is what we used for the NAB conference
# NHDplusV2_NewEngCrop_ccdvlp <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
#          PctImp_Ws = PctImp_Ws + 2,
#          pctAg_Ws = pctAg_Ws + 2,
#          logRdCrsCat = logRdCrsCat + 2,
#          huc12_damden_sqkm = huc12_damden_sqkm + 2,
#          huc8_damcount = huc8_damcount + 2
#          )


tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_dvlp_cvr, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc_dvlp_cvr, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccdvlp_cvr <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccdvlp_cvr <- temptraits_ccdvlp_cvr %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccdvlp_cvr)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp_cvr.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccdvlp_cvr, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccdvlp_cvr_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )







#prediction using climate change and management values: increase in connectivity

test <- NHDplusV2_NewEngCrop_2080 %>% 
  data.frame() %>% 
  select(7:8, 10:39) %>% 
  rename(annual_mean_summer_temp = annual_mean_summer_temp_pls_4,
         BFI_HIST = BFI_2080,
         LO7Q1DT_HIST = LO7Q1DT_2080,
         CFM_HIST = CFM_2080,
         W95_HIST = W95_2080,
         logMJJA_HIST = logMJJA_2080) %>% 
  mutate(PctImp_Ws = PctImp_Ws * .1,
         pctAg_Ws = pctAg_Ws * .1) %>% 
  select(1:2, 27:31, 3:24, 32, 25:26)


#scale the variables using the means and sd used to scale the variables in the baseline condition
test <- sweep(test, 2, means, FUN = '-') 
test <- sweep(test, 2, sd, FUN = '/')  

#join the scaled variables back to 
NHDplusV2_NewEngCrop_cc_mgmt_cvr <- cbind((NHDplusV2_NewEngCrop_2080)[,c(1:6, 9)], test)


#used for NAB
# NHDplusV2_NewEngCrop_ccmgmt <- NHDplusV2_NewEngCrop %>% 
#   mutate(annual_mean_summer_temp = annual_mean_summer_temp + 2,
#          PctImp_Ws = PctImp_Ws - 2,
#          pctAg_Ws = pctAg_Ws - 2,
#          logRdCrsCat = logRdCrsCat - 2,
#          huc12_damden_sqkm = huc12_damden_sqkm - 2,
#          huc8_damcount = huc8_damcount - 2,
#          
#          )

tmp <- predict(mdl, newdata = NHDplusV2_NewEngCrop_cc_mgmt_cvr, "probs")

#join the predictions_ccmgmt to the list of comids
tmp <- cbind(NHDplusV2_NewEngCrop_cc_mgmt_cvr, tmp)

tmp <- tmp %>%
  data.frame() %>% 
  select(huc12_name, huc12_tnmid, warm, cold, cool) %>% 
  pivot_longer(3:5, names_to = "temperature", values_to = "prop") %>% 
  group_by(huc12_name, huc12_tnmid, temperature) %>%
  summarise(mean = round(mean(prop, na.rm = T), 2),
            min = round(quantile(prop, probs = 0.05, na.rm = T), 2),
            max = round(quantile(prop, probs = 0.95, na.rm = T), 2))
  



temptraits_ccmgmt_cvr <- left_join(huc12, tmp, by = c("huc12_name", "huc12_tnmid"))


temptraits_ccmgmt_cvr <- temptraits_ccmgmt_cvr %>%  
  filter(!is.na(temperature))

ggplot(data = temptraits_ccmgmt_cvr)+
  geom_sf(aes(fill = mean), color = NA)+
  scale_fill_viridis_c(limits = c(0,1))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Avg Prop.")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt_cvr.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = temptraits_ccmgmt_cvr, aes(x = huc8_name, y = mean))+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = min, ymax = max), width = .2)+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15))+
    ggtitle(label = "Temperature Trait Proportion")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_ccmgmt_cvr_dot.png",
    plot = last_plot(),
    width = 14,
    height = 9,
    units = "cm",
    dpi = 200
  )





temptraits_baseline$scenario <- "baseline"
temptraits_cc$scenario <- "CC"
temptraits_ccdvlp_cnn$scenario <- "CC + dvlp + cnn"
temptraits_ccdvlp_cvr$scenario <- "CC + dvlp + cvr"
temptraits_ccmgmt_cnn$scenario <- "CC + Mgmt + cnn"
temptraits_ccmgmt_cvr$scenario <- "CC + Mgmt + cvr"

tmp <- bind_rows(temptraits_baseline, temptraits_cc, 
                 temptraits_ccdvlp_cnn, temptraits_ccdvlp_cvr, 
                 temptraits_ccmgmt_cnn, temptraits_ccmgmt_cvr)
tmp <- tmp %>% 
  filter(huc12_name %in% c("Sudbury Reservoir-Sudbury River", "East Branch Saco River", "Buffalo Stream"))
tmp$huc12_name[tmp$huc12_name == "Sudbury Reservoir-Sudbury River"] <- "Sudbury Reservoir"
tmp$huc12_name <- factor(tmp$huc12_name, levels = c("Sudbury Reservoir", "East Branch Saco River", "Buffalo Stream"))
tmp$scenario <- factor(tmp$scenario, levels = c("baseline", 
                                                "CC", 
                                                "CC + dvlp + cnn", 
                                                "CC + dvlp + cvr", 
                                                "CC + Mgmt + cnn",
                                                "CC + Mgmt + cvr"))

ggplot(data = tmp, aes(x = huc12_name, y = mean, color = scenario))+
  scale_color_manual(values = c("mediumpurple1", "darkgoldenrod1", "red3", "green4", "blue", "purple"))+
  geom_point(size = 2, position=position_dodge(width=0.5))+
  geom_errorbar(aes(ymin = min, ymax = max), width = .5, position=position_dodge(width=0.5))+
  geom_hline(yintercept = 0.5, color = "grey80", linetype = "dashed")+
  coord_flip()+
  facet_wrap(~temperature, nrow = 1)+
  theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        title = element_text(size = 15),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"))+
  labs(y = "Avg Proportional Abundance")+
  scale_y_continuous(limits = c(0, 1), breaks = 0.5)
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_compare_dot.png",
    plot = last_plot(),
    width = 19,
    height = 10,
    units = "cm",
    dpi = 200
  )









diff <- temptraits_baseline %>% 
  rename(baseline_mean = mean) %>% 
  mutate(cc_mean = temptraits_cc$mean,
         ccdvlp_mean = temptraits_ccdvlp$mean,
         ccmgmt_mean = temptraits_ccmgmt$mean,
         change_dvlp = ccdvlp_mean - cc_mean,
         change_mgmt = ccmgmt_mean - cc_mean)


ggplot(data = diff)+
  geom_sf(aes(fill = change_dvlp), color = NA)+
  scale_fill_viridis_c(option = "magma", limits = c(-.25, 0.25))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Change")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_dvlp_change.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )

ggplot(data = diff)+
  geom_sf(aes(fill = change_mgmt), color = NA)+
  scale_fill_viridis_c(option = "magma", limits = c(-.25, 0.25))+
  facet_wrap(~temperature, nrow = 1)+
    geom_sf(data = states, fill = NA, lwd = 0.2, color = "black")+
    theme(panel.border = element_rect(colour = "black", fill = NA),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
        strip.background = element_rect(fill = "grey50",
                                        colour = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+
    labs(fill = "Change")
ggsave(
    filename = "C:/Users/jenrogers/Documents/git/FreshwaterBio/FreshwaterBio/tmpfigures/temp_prep_prediction_cc_mmgt_change.png",
    plot = last_plot(),
    width = 14,
    height = 7,
    units = "cm",
    dpi = 200
  )


```