---
title: "Climate Change Paper Software Releas"
author: "Jenny Rogers"
date: "2023-01-25"
output: html_document
---

# Can management alleviate impacts of climate change to support freshwater fish and mussel biodiversity? 

##Authors

Jennifer B. Rogers, Massachusetts Cooperative Fish and Wildlife Research Unit, Department of Environmental Conservation, University of Massachusetts, Amherst, MA 01003, USA

Rebecca O'Brien, Massachusetts Cooperative Fish and Wildlife Research Unit, Department of Environmental Conservation, University of Massachusetts, Amherst, MA 01003, USA

Graziella V. DiRenzo, U.S. Geological Survey, Massachusetts Cooperative Fish and Wildlife Research Unit, Department of Environmental Conservation, University of Massachusetts, Amherst, MA 01003, USA 

Rebecca M. Quiñones, Massachusetts Division of Fisheries and Wildlife, 1 Rabbit Hill, Westborough, MA 01581, USA

Todd Richards, Massachusetts Division of Fisheries and Wildlife, 1 Rabbit Hill, Westborough, MA 01581, USA

Allison H. Roy, U.S. Geological Survey, Massachusetts Cooperative Fish and Wildlife Research Unit, Department of Environmental Conservation, University of Massachusetts, Amherst, MA 01003, USA


##Information

Repository Type: Program R scripts

Year of Origin: 2021

Year of Version: 2024

Version: 

Digital Object Identifier (DOI): 

USGS Information Product Data System (IPDS) no.:

## Suggested Citation for Software
Rogers, J.B., R. O'Brien, G.V. DiRenzo, R.M. Quiñones, T.Richards, A. H. Roy. 2023. Freshwater fish biodiversity and distribution in the Northeastern United States. Version 1.0.0: U.S. Geological Survey software release, https://doi.org/xxxxxx

## Abstract

This software contains X separate R Markdown files and X R script file that comprise an analysis to 1. use freshwater fish and mussel models to predict the impacts of climate change on certain groups of freshwater fish and mussel species of management intervnetions within the Northeast United state, and 2. asses the potential for different management interventions to mitigate various climate change impacts






### File 1: BiodiversityModel_ClimateChangePaper.Rmd

#### Data inputs:
fish_count_with_zeros.RData
all_fish_event.shp
fish_event_huc_join.RData
WBDHU8_NE.shp
NEWENGLAND_POLY.shp
model_covariates.RData
model_covariates_byhuc12.RData
fish_traits.RData


#### Overview: 
This R Markdown file is similar to the BiodiversityModel.Rmd file used in the Paper1, but the models use new covariates that were selected for the climate change paper that better reflect management options.  It fits 53 zero-inflated beta models for each of the fish species considered in this analysis. The models are used to predict proportional abundance and probability of occurrence of each fish species. The first part of the code prepares the dataframe by 1. filtering for the species to be modeled, 2. using the species count data to calculate proportional abundance, 3. joining the species count data to the scaled model covariate files,  and 4. setting aside 20% of the data for model validation.  The first (out of 53) model is fitted to the data and the results and validation metrics are saved in a separate dataframe.  The remaining 52 models are fitted in a 'for' loop and the model results and validation statistics are added progressively into the same results and validation dataframes.  Then a series of figures are made for the manuscript that show the model validation metrics (Figure 1 in paper 1), and a series of odds ratios that are created by averaging together model coefficients of species that fall into the same guilds and clusters (Figures 7 and 8 in paper1).

#### Outputs:
53 fish species zero inflated models
val_zero_prob.csv
prop_abun_validation.csv
raw_results.csv
propabun_results.csv
zeroinfla_results.csv
Manuscript Figure 1, 7, and 8





### File 2: BiodiversityModel_Mussel_HUC12.Rmd

#### Data inputs:


#### Overview: 
In this script we fit 12 models for the probability of freshwater mussel occurrence at the HUC12 scale for each species individually. First, the host fish covariates are calcuated by loading the fish models and predicting the baseline presence/absence and proportional abundance of each fish species. Then we train 12 logistic regression models for each mussel species using 80% of the mussel occurrence records and saving 20% for model validation. The models are fitted in separately, rather than in a 'for' loop, because host fish specialists had additional covariates beyond the variables used in the generalist models. Additionally, if the species had fewer than 100 postive occurrences in the data set, we used a lower threshold probability of occurrence to assign a 'presence' prediction when validating the model. Validation metrics and the model results are 'rbinded' together.

#### Outputs:





### File 3: BiodiversityModelPrediction_Mussel_HUC12_ClimateChangePaper.Rmd

#### Data inputs:


#### Overview: 
In this script, we apply the models that were calibrated in the above .Rmd file to estimate the probability of freshwater fish and freshwater mussel occurrence at the HUC12 scale in five different scenarios: baseline, climate change (cc), cc + riparian imperviousness = 0, cc + riparian natural = 0, cc + watershed forest = 100, cc + dam density = 0, and a final scenario that combines all of the above + cc.  The probabilites of occurrence of each fish species and each mussel species are saved for each of the scenarios.  For each scenario, first the 53 fish models are loaded and fish probablities of occurrence are estimated and then the host fish variables are calcuated. Then the 12 mussel models are loaded and applied using the host fish variables and the mussel probabilies of occurrence are modeled and saved.


#### Outputs:



### File 4: BiodiversityMetricCalculations_ClimateChangePaper.Rmd


#### Data inputs:


#### Overview: 
This script makes the final figures for the paper that show probabliies of fish and mussel occurrence after combining species into trait groups and clusters.  Probabilities of occurrence for each fish and mussel species are loaded and then each fish and mussel species is assigned a series of traits. The probabiliesi are then combined by trait and summed proabiles of occurrence are calucted for each scenario. Additionally, mussel species richness is calcuated.

#### Outputs:

